/*
 * This file is generated by jOOQ.
 */
package tjcbs.jooq.db;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import tjcbs.jooq.db.tables.CbsAccount;
import tjcbs.jooq.db.tables.CbsCreditAccount;
import tjcbs.jooq.db.tables.CbsCreditAccountLimit;
import tjcbs.jooq.db.tables.CbsCustomer;
import tjcbs.jooq.db.tables.CbsCustomerAddress;
import tjcbs.jooq.db.tables.CbsCustomerEmails;
import tjcbs.jooq.db.tables.CbsInfo;
import tjcbs.jooq.db.tables.CbsProducts;
import tjcbs.jooq.db.tables.CbsSavingsAccount;
import tjcbs.jooq.db.tables.CbsSavingsAccountLimit;
import tjcbs.jooq.db.tables.CbsSavingsTransactions;
import tjcbs.jooq.db.tables.CbsSimpleLoan;
import tjcbs.jooq.db.tables.CbsSimpleLoanPaymentSchedule;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class App extends SchemaImpl {

    private static final long serialVersionUID = 330996777;

    /**
     * The reference instance of <code>APP</code>
     */
    public static final App APP = new App();

    /**
     * The table <code>APP.CBS_ACCOUNT</code>.
     */
    public final CbsAccount CBS_ACCOUNT = tjcbs.jooq.db.tables.CbsAccount.CBS_ACCOUNT;

    /**
     * The table <code>APP.CBS_CREDIT_ACCOUNT</code>.
     */
    public final CbsCreditAccount CBS_CREDIT_ACCOUNT = tjcbs.jooq.db.tables.CbsCreditAccount.CBS_CREDIT_ACCOUNT;

    /**
     * The table <code>APP.CBS_CREDIT_ACCOUNT_LIMIT</code>.
     */
    public final CbsCreditAccountLimit CBS_CREDIT_ACCOUNT_LIMIT = tjcbs.jooq.db.tables.CbsCreditAccountLimit.CBS_CREDIT_ACCOUNT_LIMIT;

    /**
     * The table <code>APP.CBS_CUSTOMER</code>.
     */
    public final CbsCustomer CBS_CUSTOMER = tjcbs.jooq.db.tables.CbsCustomer.CBS_CUSTOMER;

    /**
     * The table <code>APP.CBS_CUSTOMER_ADDRESS</code>.
     */
    public final CbsCustomerAddress CBS_CUSTOMER_ADDRESS = tjcbs.jooq.db.tables.CbsCustomerAddress.CBS_CUSTOMER_ADDRESS;

    /**
     * The table <code>APP.CBS_CUSTOMER_EMAILS</code>.
     */
    public final CbsCustomerEmails CBS_CUSTOMER_EMAILS = tjcbs.jooq.db.tables.CbsCustomerEmails.CBS_CUSTOMER_EMAILS;

    /**
     * The table <code>APP.CBS_INFO</code>.
     */
    public final CbsInfo CBS_INFO = tjcbs.jooq.db.tables.CbsInfo.CBS_INFO;

    /**
     * The table <code>APP.CBS_PRODUCTS</code>.
     */
    public final CbsProducts CBS_PRODUCTS = tjcbs.jooq.db.tables.CbsProducts.CBS_PRODUCTS;

    /**
     * The table <code>APP.CBS_SAVINGS_ACCOUNT</code>.
     */
    public final CbsSavingsAccount CBS_SAVINGS_ACCOUNT = tjcbs.jooq.db.tables.CbsSavingsAccount.CBS_SAVINGS_ACCOUNT;

    /**
     * The table <code>APP.CBS_SAVINGS_ACCOUNT_LIMIT</code>.
     */
    public final CbsSavingsAccountLimit CBS_SAVINGS_ACCOUNT_LIMIT = tjcbs.jooq.db.tables.CbsSavingsAccountLimit.CBS_SAVINGS_ACCOUNT_LIMIT;

    /**
     * The table <code>APP.CBS_SAVINGS_TRANSACTIONS</code>.
     */
    public final CbsSavingsTransactions CBS_SAVINGS_TRANSACTIONS = tjcbs.jooq.db.tables.CbsSavingsTransactions.CBS_SAVINGS_TRANSACTIONS;

    /**
     * The table <code>APP.CBS_SIMPLE_LOAN</code>.
     */
    public final CbsSimpleLoan CBS_SIMPLE_LOAN = tjcbs.jooq.db.tables.CbsSimpleLoan.CBS_SIMPLE_LOAN;

    /**
     * The table <code>APP.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE</code>.
     */
    public final CbsSimpleLoanPaymentSchedule CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE = tjcbs.jooq.db.tables.CbsSimpleLoanPaymentSchedule.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE;

    /**
     * No further instances allowed
     */
    private App() {
        super("APP", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            CbsAccount.CBS_ACCOUNT,
            CbsCreditAccount.CBS_CREDIT_ACCOUNT,
            CbsCreditAccountLimit.CBS_CREDIT_ACCOUNT_LIMIT,
            CbsCustomer.CBS_CUSTOMER,
            CbsCustomerAddress.CBS_CUSTOMER_ADDRESS,
            CbsCustomerEmails.CBS_CUSTOMER_EMAILS,
            CbsInfo.CBS_INFO,
            CbsProducts.CBS_PRODUCTS,
            CbsSavingsAccount.CBS_SAVINGS_ACCOUNT,
            CbsSavingsAccountLimit.CBS_SAVINGS_ACCOUNT_LIMIT,
            CbsSavingsTransactions.CBS_SAVINGS_TRANSACTIONS,
            CbsSimpleLoan.CBS_SIMPLE_LOAN,
            CbsSimpleLoanPaymentSchedule.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE);
    }
}
