/*
 * This file is generated by jOOQ.
 */
package tjcbs.jooq.db;


import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import tjcbs.jooq.db.tables.CbsAccount;
import tjcbs.jooq.db.tables.CbsCreditAccount;
import tjcbs.jooq.db.tables.CbsCreditAccountLimit;
import tjcbs.jooq.db.tables.CbsCustomer;
import tjcbs.jooq.db.tables.CbsCustomerAddress;
import tjcbs.jooq.db.tables.CbsCustomerEmails;
import tjcbs.jooq.db.tables.CbsInfo;
import tjcbs.jooq.db.tables.CbsProducts;
import tjcbs.jooq.db.tables.CbsSavingsAccount;
import tjcbs.jooq.db.tables.CbsSavingsAccountLimit;
import tjcbs.jooq.db.tables.CbsSavingsTransactions;
import tjcbs.jooq.db.tables.CbsSimpleLoan;
import tjcbs.jooq.db.tables.CbsSimpleLoanPaymentSchedule;
import tjcbs.jooq.db.tables.records.CbsAccountRecord;
import tjcbs.jooq.db.tables.records.CbsCreditAccountLimitRecord;
import tjcbs.jooq.db.tables.records.CbsCreditAccountRecord;
import tjcbs.jooq.db.tables.records.CbsCustomerAddressRecord;
import tjcbs.jooq.db.tables.records.CbsCustomerEmailsRecord;
import tjcbs.jooq.db.tables.records.CbsCustomerRecord;
import tjcbs.jooq.db.tables.records.CbsInfoRecord;
import tjcbs.jooq.db.tables.records.CbsProductsRecord;
import tjcbs.jooq.db.tables.records.CbsSavingsAccountLimitRecord;
import tjcbs.jooq.db.tables.records.CbsSavingsAccountRecord;
import tjcbs.jooq.db.tables.records.CbsSavingsTransactionsRecord;
import tjcbs.jooq.db.tables.records.CbsSimpleLoanPaymentScheduleRecord;
import tjcbs.jooq.db.tables.records.CbsSimpleLoanRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>APP</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CbsAccountRecord> CBS_ACCOUNT_PK = UniqueKeys0.CBS_ACCOUNT_PK;
    public static final UniqueKey<CbsCreditAccountRecord> CBS_SAVINGS_ACCOUNTR_PK = UniqueKeys0.CBS_SAVINGS_ACCOUNTR_PK;
    public static final UniqueKey<CbsCreditAccountLimitRecord> CBS_CREDIT_ACCOUNT_LIMIT_PK = UniqueKeys0.CBS_CREDIT_ACCOUNT_LIMIT_PK;
    public static final UniqueKey<CbsCustomerRecord> CBS_CUSTOMER_PK = UniqueKeys0.CBS_CUSTOMER_PK;
    public static final UniqueKey<CbsInfoRecord> CBS_INFO_PK = UniqueKeys0.CBS_INFO_PK;
    public static final UniqueKey<CbsProductsRecord> CBS_PRODUCTS_PK = UniqueKeys0.CBS_PRODUCTS_PK;
    public static final UniqueKey<CbsSavingsAccountRecord> CBS_SAVINGS_ACCOUNT_PK = UniqueKeys0.CBS_SAVINGS_ACCOUNT_PK;
    public static final UniqueKey<CbsSavingsAccountLimitRecord> CBS_SAVINGS_ACCOUNT_LIMIT_PK = UniqueKeys0.CBS_SAVINGS_ACCOUNT_LIMIT_PK;
    public static final UniqueKey<CbsSavingsTransactionsRecord> CBS_SAVINGS_TRANSACTIONS_PK = UniqueKeys0.CBS_SAVINGS_TRANSACTIONS_PK;
    public static final UniqueKey<CbsSimpleLoanRecord> CBS_SIMPLE_LOAN_PK = UniqueKeys0.CBS_SIMPLE_LOAN_PK;
    public static final UniqueKey<CbsSimpleLoanPaymentScheduleRecord> CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE_PK = UniqueKeys0.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE_PK;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CbsCreditAccountRecord, CbsCustomerRecord> SQL181029115214490 = ForeignKeys0.SQL181029115214490;
    public static final ForeignKey<CbsCreditAccountLimitRecord, CbsCustomerRecord> SQL181029115214530 = ForeignKeys0.SQL181029115214530;
    public static final ForeignKey<CbsCustomerAddressRecord, CbsCustomerRecord> SQL181029115214320 = ForeignKeys0.SQL181029115214320;
    public static final ForeignKey<CbsCustomerEmailsRecord, CbsCustomerRecord> SQL181029115214280 = ForeignKeys0.SQL181029115214280;
    public static final ForeignKey<CbsSavingsAccountRecord, CbsCustomerRecord> SQL181029115214370 = ForeignKeys0.SQL181029115214370;
    public static final ForeignKey<CbsSavingsAccountLimitRecord, CbsCustomerRecord> SQL181029115214460 = ForeignKeys0.SQL181029115214460;
    public static final ForeignKey<CbsSavingsTransactionsRecord, CbsSavingsAccountRecord> SQL181029115214420 = ForeignKeys0.SQL181029115214420;
    public static final ForeignKey<CbsSimpleLoanRecord, CbsCustomerRecord> SQL181029115214590 = ForeignKeys0.SQL181029115214590;
    public static final ForeignKey<CbsSimpleLoanPaymentScheduleRecord, CbsSimpleLoanRecord> SQL181029115214640 = ForeignKeys0.SQL181029115214640;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<CbsAccountRecord> CBS_ACCOUNT_PK = Internal.createUniqueKey(CbsAccount.CBS_ACCOUNT, "CBS_ACCOUNT_PK", CbsAccount.CBS_ACCOUNT.ID);
        public static final UniqueKey<CbsCreditAccountRecord> CBS_SAVINGS_ACCOUNTR_PK = Internal.createUniqueKey(CbsCreditAccount.CBS_CREDIT_ACCOUNT, "CBS_SAVINGS_ACCOUNTR_PK", CbsCreditAccount.CBS_CREDIT_ACCOUNT.ID, CbsCreditAccount.CBS_CREDIT_ACCOUNT.NINO);
        public static final UniqueKey<CbsCreditAccountLimitRecord> CBS_CREDIT_ACCOUNT_LIMIT_PK = Internal.createUniqueKey(CbsCreditAccountLimit.CBS_CREDIT_ACCOUNT_LIMIT, "CBS_CREDIT_ACCOUNT_LIMIT_PK", CbsCreditAccountLimit.CBS_CREDIT_ACCOUNT_LIMIT.ID, CbsCreditAccountLimit.CBS_CREDIT_ACCOUNT_LIMIT.NINO);
        public static final UniqueKey<CbsCustomerRecord> CBS_CUSTOMER_PK = Internal.createUniqueKey(CbsCustomer.CBS_CUSTOMER, "CBS_CUSTOMER_PK", CbsCustomer.CBS_CUSTOMER.NINO);
        public static final UniqueKey<CbsInfoRecord> CBS_INFO_PK = Internal.createUniqueKey(CbsInfo.CBS_INFO, "CBS_INFO_PK", CbsInfo.CBS_INFO.PARTNER_ID);
        public static final UniqueKey<CbsProductsRecord> CBS_PRODUCTS_PK = Internal.createUniqueKey(CbsProducts.CBS_PRODUCTS, "CBS_PRODUCTS_PK", CbsProducts.CBS_PRODUCTS.PARTNER_ID, CbsProducts.CBS_PRODUCTS.PRODUCT);
        public static final UniqueKey<CbsSavingsAccountRecord> CBS_SAVINGS_ACCOUNT_PK = Internal.createUniqueKey(CbsSavingsAccount.CBS_SAVINGS_ACCOUNT, "CBS_SAVINGS_ACCOUNT_PK", CbsSavingsAccount.CBS_SAVINGS_ACCOUNT.ID, CbsSavingsAccount.CBS_SAVINGS_ACCOUNT.NINO);
        public static final UniqueKey<CbsSavingsAccountLimitRecord> CBS_SAVINGS_ACCOUNT_LIMIT_PK = Internal.createUniqueKey(CbsSavingsAccountLimit.CBS_SAVINGS_ACCOUNT_LIMIT, "CBS_SAVINGS_ACCOUNT_LIMIT_PK", CbsSavingsAccountLimit.CBS_SAVINGS_ACCOUNT_LIMIT.ID, CbsSavingsAccountLimit.CBS_SAVINGS_ACCOUNT_LIMIT.NINO);
        public static final UniqueKey<CbsSavingsTransactionsRecord> CBS_SAVINGS_TRANSACTIONS_PK = Internal.createUniqueKey(CbsSavingsTransactions.CBS_SAVINGS_TRANSACTIONS, "CBS_SAVINGS_TRANSACTIONS_PK", CbsSavingsTransactions.CBS_SAVINGS_TRANSACTIONS.ID, CbsSavingsTransactions.CBS_SAVINGS_TRANSACTIONS.NINO, CbsSavingsTransactions.CBS_SAVINGS_TRANSACTIONS.TXID);
        public static final UniqueKey<CbsSimpleLoanRecord> CBS_SIMPLE_LOAN_PK = Internal.createUniqueKey(CbsSimpleLoan.CBS_SIMPLE_LOAN, "CBS_SIMPLE_LOAN_PK", CbsSimpleLoan.CBS_SIMPLE_LOAN.ID, CbsSimpleLoan.CBS_SIMPLE_LOAN.NINO);
        public static final UniqueKey<CbsSimpleLoanPaymentScheduleRecord> CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE_PK = Internal.createUniqueKey(CbsSimpleLoanPaymentSchedule.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE, "CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE_PK", CbsSimpleLoanPaymentSchedule.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.ID, CbsSimpleLoanPaymentSchedule.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.LOAN_ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<CbsCreditAccountRecord, CbsCustomerRecord> SQL181029115214490 = Internal.createForeignKey(tjcbs.jooq.db.Keys.CBS_CUSTOMER_PK, CbsCreditAccount.CBS_CREDIT_ACCOUNT, "SQL181029115214490", CbsCreditAccount.CBS_CREDIT_ACCOUNT.NINO);
        public static final ForeignKey<CbsCreditAccountLimitRecord, CbsCustomerRecord> SQL181029115214530 = Internal.createForeignKey(tjcbs.jooq.db.Keys.CBS_CUSTOMER_PK, CbsCreditAccountLimit.CBS_CREDIT_ACCOUNT_LIMIT, "SQL181029115214530", CbsCreditAccountLimit.CBS_CREDIT_ACCOUNT_LIMIT.NINO);
        public static final ForeignKey<CbsCustomerAddressRecord, CbsCustomerRecord> SQL181029115214320 = Internal.createForeignKey(tjcbs.jooq.db.Keys.CBS_CUSTOMER_PK, CbsCustomerAddress.CBS_CUSTOMER_ADDRESS, "SQL181029115214320", CbsCustomerAddress.CBS_CUSTOMER_ADDRESS.NINO);
        public static final ForeignKey<CbsCustomerEmailsRecord, CbsCustomerRecord> SQL181029115214280 = Internal.createForeignKey(tjcbs.jooq.db.Keys.CBS_CUSTOMER_PK, CbsCustomerEmails.CBS_CUSTOMER_EMAILS, "SQL181029115214280", CbsCustomerEmails.CBS_CUSTOMER_EMAILS.NINO);
        public static final ForeignKey<CbsSavingsAccountRecord, CbsCustomerRecord> SQL181029115214370 = Internal.createForeignKey(tjcbs.jooq.db.Keys.CBS_CUSTOMER_PK, CbsSavingsAccount.CBS_SAVINGS_ACCOUNT, "SQL181029115214370", CbsSavingsAccount.CBS_SAVINGS_ACCOUNT.NINO);
        public static final ForeignKey<CbsSavingsAccountLimitRecord, CbsCustomerRecord> SQL181029115214460 = Internal.createForeignKey(tjcbs.jooq.db.Keys.CBS_CUSTOMER_PK, CbsSavingsAccountLimit.CBS_SAVINGS_ACCOUNT_LIMIT, "SQL181029115214460", CbsSavingsAccountLimit.CBS_SAVINGS_ACCOUNT_LIMIT.NINO);
        public static final ForeignKey<CbsSavingsTransactionsRecord, CbsSavingsAccountRecord> SQL181029115214420 = Internal.createForeignKey(tjcbs.jooq.db.Keys.CBS_SAVINGS_ACCOUNT_PK, CbsSavingsTransactions.CBS_SAVINGS_TRANSACTIONS, "SQL181029115214420", CbsSavingsTransactions.CBS_SAVINGS_TRANSACTIONS.ID, CbsSavingsTransactions.CBS_SAVINGS_TRANSACTIONS.NINO);
        public static final ForeignKey<CbsSimpleLoanRecord, CbsCustomerRecord> SQL181029115214590 = Internal.createForeignKey(tjcbs.jooq.db.Keys.CBS_CUSTOMER_PK, CbsSimpleLoan.CBS_SIMPLE_LOAN, "SQL181029115214590", CbsSimpleLoan.CBS_SIMPLE_LOAN.NINO);
        public static final ForeignKey<CbsSimpleLoanPaymentScheduleRecord, CbsSimpleLoanRecord> SQL181029115214640 = Internal.createForeignKey(tjcbs.jooq.db.Keys.CBS_SIMPLE_LOAN_PK, CbsSimpleLoanPaymentSchedule.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE, "SQL181029115214640", CbsSimpleLoanPaymentSchedule.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.LOAN_ID, CbsSimpleLoanPaymentSchedule.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.NINO);
    }
}
