/*
 * This file is generated by jOOQ.
 */
package tjcbs.jooq.db;


import javax.annotation.Generated;

import tjcbs.jooq.db.tables.CbsAccount;
import tjcbs.jooq.db.tables.CbsCreditAccount;
import tjcbs.jooq.db.tables.CbsCreditAccountLimit;
import tjcbs.jooq.db.tables.CbsCustomer;
import tjcbs.jooq.db.tables.CbsCustomerAddress;
import tjcbs.jooq.db.tables.CbsCustomerEmails;
import tjcbs.jooq.db.tables.CbsInfo;
import tjcbs.jooq.db.tables.CbsProducts;
import tjcbs.jooq.db.tables.CbsSavingsAccount;
import tjcbs.jooq.db.tables.CbsSavingsAccountLimit;
import tjcbs.jooq.db.tables.CbsSavingsTransactions;
import tjcbs.jooq.db.tables.CbsSimpleLoan;
import tjcbs.jooq.db.tables.CbsSimpleLoanPaymentSchedule;


/**
 * Convenience access to all tables in APP
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>APP.CBS_ACCOUNT</code>.
     */
    public static final CbsAccount CBS_ACCOUNT = tjcbs.jooq.db.tables.CbsAccount.CBS_ACCOUNT;

    /**
     * The table <code>APP.CBS_CREDIT_ACCOUNT</code>.
     */
    public static final CbsCreditAccount CBS_CREDIT_ACCOUNT = tjcbs.jooq.db.tables.CbsCreditAccount.CBS_CREDIT_ACCOUNT;

    /**
     * The table <code>APP.CBS_CREDIT_ACCOUNT_LIMIT</code>.
     */
    public static final CbsCreditAccountLimit CBS_CREDIT_ACCOUNT_LIMIT = tjcbs.jooq.db.tables.CbsCreditAccountLimit.CBS_CREDIT_ACCOUNT_LIMIT;

    /**
     * The table <code>APP.CBS_CUSTOMER</code>.
     */
    public static final CbsCustomer CBS_CUSTOMER = tjcbs.jooq.db.tables.CbsCustomer.CBS_CUSTOMER;

    /**
     * The table <code>APP.CBS_CUSTOMER_ADDRESS</code>.
     */
    public static final CbsCustomerAddress CBS_CUSTOMER_ADDRESS = tjcbs.jooq.db.tables.CbsCustomerAddress.CBS_CUSTOMER_ADDRESS;

    /**
     * The table <code>APP.CBS_CUSTOMER_EMAILS</code>.
     */
    public static final CbsCustomerEmails CBS_CUSTOMER_EMAILS = tjcbs.jooq.db.tables.CbsCustomerEmails.CBS_CUSTOMER_EMAILS;

    /**
     * The table <code>APP.CBS_INFO</code>.
     */
    public static final CbsInfo CBS_INFO = tjcbs.jooq.db.tables.CbsInfo.CBS_INFO;

    /**
     * The table <code>APP.CBS_PRODUCTS</code>.
     */
    public static final CbsProducts CBS_PRODUCTS = tjcbs.jooq.db.tables.CbsProducts.CBS_PRODUCTS;

    /**
     * The table <code>APP.CBS_SAVINGS_ACCOUNT</code>.
     */
    public static final CbsSavingsAccount CBS_SAVINGS_ACCOUNT = tjcbs.jooq.db.tables.CbsSavingsAccount.CBS_SAVINGS_ACCOUNT;

    /**
     * The table <code>APP.CBS_SAVINGS_ACCOUNT_LIMIT</code>.
     */
    public static final CbsSavingsAccountLimit CBS_SAVINGS_ACCOUNT_LIMIT = tjcbs.jooq.db.tables.CbsSavingsAccountLimit.CBS_SAVINGS_ACCOUNT_LIMIT;

    /**
     * The table <code>APP.CBS_SAVINGS_TRANSACTIONS</code>.
     */
    public static final CbsSavingsTransactions CBS_SAVINGS_TRANSACTIONS = tjcbs.jooq.db.tables.CbsSavingsTransactions.CBS_SAVINGS_TRANSACTIONS;

    /**
     * The table <code>APP.CBS_SIMPLE_LOAN</code>.
     */
    public static final CbsSimpleLoan CBS_SIMPLE_LOAN = tjcbs.jooq.db.tables.CbsSimpleLoan.CBS_SIMPLE_LOAN;

    /**
     * The table <code>APP.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE</code>.
     */
    public static final CbsSimpleLoanPaymentSchedule CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE = tjcbs.jooq.db.tables.CbsSimpleLoanPaymentSchedule.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE;
}
