/*
 * This file is generated by jOOQ.
 */
package tjcbs.jooq.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import tjcbs.jooq.db.App;
import tjcbs.jooq.db.Keys;
import tjcbs.jooq.db.tables.records.CbsCreditAccountRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CbsCreditAccount extends TableImpl<CbsCreditAccountRecord> {

    private static final long serialVersionUID = 617062175;

    /**
     * The reference instance of <code>APP.CBS_CREDIT_ACCOUNT</code>
     */
    public static final CbsCreditAccount CBS_CREDIT_ACCOUNT = new CbsCreditAccount();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CbsCreditAccountRecord> getRecordType() {
        return CbsCreditAccountRecord.class;
    }

    /**
     * The column <code>APP.CBS_CREDIT_ACCOUNT.ID</code>.
     */
    public final TableField<CbsCreditAccountRecord, String> ID = createField("ID", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>APP.CBS_CREDIT_ACCOUNT.NINO</code>.
     */
    public final TableField<CbsCreditAccountRecord, String> NINO = createField("NINO", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>APP.CBS_CREDIT_ACCOUNT.NAME</code>.
     */
    public final TableField<CbsCreditAccountRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>APP.CBS_CREDIT_ACCOUNT.LABEL</code>.
     */
    public final TableField<CbsCreditAccountRecord, String> LABEL = createField("LABEL", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>APP.CBS_CREDIT_ACCOUNT.TDATE</code>.
     */
    public final TableField<CbsCreditAccountRecord, Integer> TDATE = createField("TDATE", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>APP.CBS_CREDIT_ACCOUNT.TTIME</code>.
     */
    public final TableField<CbsCreditAccountRecord, Integer> TTIME = createField("TTIME", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>APP.CBS_CREDIT_ACCOUNT.AMOUNT</code>.
     */
    public final TableField<CbsCreditAccountRecord, Double> AMOUNT = createField("AMOUNT", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * Create a <code>APP.CBS_CREDIT_ACCOUNT</code> table reference
     */
    public CbsCreditAccount() {
        this(DSL.name("CBS_CREDIT_ACCOUNT"), null);
    }

    /**
     * Create an aliased <code>APP.CBS_CREDIT_ACCOUNT</code> table reference
     */
    public CbsCreditAccount(String alias) {
        this(DSL.name(alias), CBS_CREDIT_ACCOUNT);
    }

    /**
     * Create an aliased <code>APP.CBS_CREDIT_ACCOUNT</code> table reference
     */
    public CbsCreditAccount(Name alias) {
        this(alias, CBS_CREDIT_ACCOUNT);
    }

    private CbsCreditAccount(Name alias, Table<CbsCreditAccountRecord> aliased) {
        this(alias, aliased, null);
    }

    private CbsCreditAccount(Name alias, Table<CbsCreditAccountRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> CbsCreditAccount(Table<O> child, ForeignKey<O, CbsCreditAccountRecord> key) {
        super(child, key, CBS_CREDIT_ACCOUNT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return App.APP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CbsCreditAccountRecord> getPrimaryKey() {
        return Keys.CBS_SAVINGS_ACCOUNTR_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CbsCreditAccountRecord>> getKeys() {
        return Arrays.<UniqueKey<CbsCreditAccountRecord>>asList(Keys.CBS_SAVINGS_ACCOUNTR_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<CbsCreditAccountRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CbsCreditAccountRecord, ?>>asList(Keys.SQL181029115214490);
    }

    public CbsCustomer cbsCustomer() {
        return new CbsCustomer(this, Keys.SQL181029115214490);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsCreditAccount as(String alias) {
        return new CbsCreditAccount(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsCreditAccount as(Name alias) {
        return new CbsCreditAccount(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CbsCreditAccount rename(String name) {
        return new CbsCreditAccount(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CbsCreditAccount rename(Name name) {
        return new CbsCreditAccount(name, null);
    }
}
