/*
 * This file is generated by jOOQ.
 */
package tjcbs.jooq.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import tjcbs.jooq.db.App;
import tjcbs.jooq.db.Keys;
import tjcbs.jooq.db.tables.records.CbsCreditAccountLimitRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CbsCreditAccountLimit extends TableImpl<CbsCreditAccountLimitRecord> {

    private static final long serialVersionUID = 1937009455;

    /**
     * The reference instance of <code>APP.CBS_CREDIT_ACCOUNT_LIMIT</code>
     */
    public static final CbsCreditAccountLimit CBS_CREDIT_ACCOUNT_LIMIT = new CbsCreditAccountLimit();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CbsCreditAccountLimitRecord> getRecordType() {
        return CbsCreditAccountLimitRecord.class;
    }

    /**
     * The column <code>APP.CBS_CREDIT_ACCOUNT_LIMIT.ID</code>.
     */
    public final TableField<CbsCreditAccountLimitRecord, String> ID = createField("ID", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>APP.CBS_CREDIT_ACCOUNT_LIMIT.NINO</code>.
     */
    public final TableField<CbsCreditAccountLimitRecord, String> NINO = createField("NINO", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>APP.CBS_CREDIT_ACCOUNT_LIMIT.MAXIMUM_OVERDRAFT</code>.
     */
    public final TableField<CbsCreditAccountLimitRecord, Integer> MAXIMUM_OVERDRAFT = createField("MAXIMUM_OVERDRAFT", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>APP.CBS_CREDIT_ACCOUNT_LIMIT</code> table reference
     */
    public CbsCreditAccountLimit() {
        this(DSL.name("CBS_CREDIT_ACCOUNT_LIMIT"), null);
    }

    /**
     * Create an aliased <code>APP.CBS_CREDIT_ACCOUNT_LIMIT</code> table reference
     */
    public CbsCreditAccountLimit(String alias) {
        this(DSL.name(alias), CBS_CREDIT_ACCOUNT_LIMIT);
    }

    /**
     * Create an aliased <code>APP.CBS_CREDIT_ACCOUNT_LIMIT</code> table reference
     */
    public CbsCreditAccountLimit(Name alias) {
        this(alias, CBS_CREDIT_ACCOUNT_LIMIT);
    }

    private CbsCreditAccountLimit(Name alias, Table<CbsCreditAccountLimitRecord> aliased) {
        this(alias, aliased, null);
    }

    private CbsCreditAccountLimit(Name alias, Table<CbsCreditAccountLimitRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> CbsCreditAccountLimit(Table<O> child, ForeignKey<O, CbsCreditAccountLimitRecord> key) {
        super(child, key, CBS_CREDIT_ACCOUNT_LIMIT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return App.APP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CbsCreditAccountLimitRecord> getPrimaryKey() {
        return Keys.CBS_CREDIT_ACCOUNT_LIMIT_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CbsCreditAccountLimitRecord>> getKeys() {
        return Arrays.<UniqueKey<CbsCreditAccountLimitRecord>>asList(Keys.CBS_CREDIT_ACCOUNT_LIMIT_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<CbsCreditAccountLimitRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CbsCreditAccountLimitRecord, ?>>asList(Keys.SQL181029115214530);
    }

    public CbsCustomer cbsCustomer() {
        return new CbsCustomer(this, Keys.SQL181029115214530);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsCreditAccountLimit as(String alias) {
        return new CbsCreditAccountLimit(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsCreditAccountLimit as(Name alias) {
        return new CbsCreditAccountLimit(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CbsCreditAccountLimit rename(String name) {
        return new CbsCreditAccountLimit(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CbsCreditAccountLimit rename(Name name) {
        return new CbsCreditAccountLimit(name, null);
    }
}
