/*
 * This file is generated by jOOQ.
 */
package tjcbs.jooq.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import tjcbs.jooq.db.App;
import tjcbs.jooq.db.Keys;
import tjcbs.jooq.db.tables.records.CbsCustomerAddressRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CbsCustomerAddress extends TableImpl<CbsCustomerAddressRecord> {

    private static final long serialVersionUID = 1045508665;

    /**
     * The reference instance of <code>APP.CBS_CUSTOMER_ADDRESS</code>
     */
    public static final CbsCustomerAddress CBS_CUSTOMER_ADDRESS = new CbsCustomerAddress();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CbsCustomerAddressRecord> getRecordType() {
        return CbsCustomerAddressRecord.class;
    }

    /**
     * The column <code>APP.CBS_CUSTOMER_ADDRESS.NINO</code>.
     */
    public final TableField<CbsCustomerAddressRecord, String> NINO = createField("NINO", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>APP.CBS_CUSTOMER_ADDRESS.ADDRESS_LINE_1</code>.
     */
    public final TableField<CbsCustomerAddressRecord, String> ADDRESS_LINE_1 = createField("ADDRESS_LINE_1", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>APP.CBS_CUSTOMER_ADDRESS.ADDRESS_LINE_2</code>.
     */
    public final TableField<CbsCustomerAddressRecord, String> ADDRESS_LINE_2 = createField("ADDRESS_LINE_2", org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>APP.CBS_CUSTOMER_ADDRESS.ADDRESS_LINE_3</code>.
     */
    public final TableField<CbsCustomerAddressRecord, String> ADDRESS_LINE_3 = createField("ADDRESS_LINE_3", org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>APP.CBS_CUSTOMER_ADDRESS.CITY</code>.
     */
    public final TableField<CbsCustomerAddressRecord, String> CITY = createField("CITY", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>APP.CBS_CUSTOMER_ADDRESS.PROVINCE</code>.
     */
    public final TableField<CbsCustomerAddressRecord, String> PROVINCE = createField("PROVINCE", org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>APP.CBS_CUSTOMER_ADDRESS.POSTCODE</code>.
     */
    public final TableField<CbsCustomerAddressRecord, String> POSTCODE = createField("POSTCODE", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>APP.CBS_CUSTOMER_ADDRESS.COUNTRY</code>.
     */
    public final TableField<CbsCustomerAddressRecord, String> COUNTRY = createField("COUNTRY", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * Create a <code>APP.CBS_CUSTOMER_ADDRESS</code> table reference
     */
    public CbsCustomerAddress() {
        this(DSL.name("CBS_CUSTOMER_ADDRESS"), null);
    }

    /**
     * Create an aliased <code>APP.CBS_CUSTOMER_ADDRESS</code> table reference
     */
    public CbsCustomerAddress(String alias) {
        this(DSL.name(alias), CBS_CUSTOMER_ADDRESS);
    }

    /**
     * Create an aliased <code>APP.CBS_CUSTOMER_ADDRESS</code> table reference
     */
    public CbsCustomerAddress(Name alias) {
        this(alias, CBS_CUSTOMER_ADDRESS);
    }

    private CbsCustomerAddress(Name alias, Table<CbsCustomerAddressRecord> aliased) {
        this(alias, aliased, null);
    }

    private CbsCustomerAddress(Name alias, Table<CbsCustomerAddressRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> CbsCustomerAddress(Table<O> child, ForeignKey<O, CbsCustomerAddressRecord> key) {
        super(child, key, CBS_CUSTOMER_ADDRESS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return App.APP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<CbsCustomerAddressRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CbsCustomerAddressRecord, ?>>asList(Keys.SQL181029115214320);
    }

    public CbsCustomer cbsCustomer() {
        return new CbsCustomer(this, Keys.SQL181029115214320);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsCustomerAddress as(String alias) {
        return new CbsCustomerAddress(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsCustomerAddress as(Name alias) {
        return new CbsCustomerAddress(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CbsCustomerAddress rename(String name) {
        return new CbsCustomerAddress(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CbsCustomerAddress rename(Name name) {
        return new CbsCustomerAddress(name, null);
    }
}
