/*
 * This file is generated by jOOQ.
 */
package tjcbs.jooq.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import tjcbs.jooq.db.App;
import tjcbs.jooq.db.Keys;
import tjcbs.jooq.db.tables.records.CbsProductsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CbsProducts extends TableImpl<CbsProductsRecord> {

    private static final long serialVersionUID = -1876657320;

    /**
     * The reference instance of <code>APP.CBS_PRODUCTS</code>
     */
    public static final CbsProducts CBS_PRODUCTS = new CbsProducts();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CbsProductsRecord> getRecordType() {
        return CbsProductsRecord.class;
    }

    /**
     * The column <code>APP.CBS_PRODUCTS.PARTNER_ID</code>.
     */
    public final TableField<CbsProductsRecord, String> PARTNER_ID = createField("PARTNER_ID", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>APP.CBS_PRODUCTS.PRODUCT</code>.
     */
    public final TableField<CbsProductsRecord, String> PRODUCT = createField("PRODUCT", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * Create a <code>APP.CBS_PRODUCTS</code> table reference
     */
    public CbsProducts() {
        this(DSL.name("CBS_PRODUCTS"), null);
    }

    /**
     * Create an aliased <code>APP.CBS_PRODUCTS</code> table reference
     */
    public CbsProducts(String alias) {
        this(DSL.name(alias), CBS_PRODUCTS);
    }

    /**
     * Create an aliased <code>APP.CBS_PRODUCTS</code> table reference
     */
    public CbsProducts(Name alias) {
        this(alias, CBS_PRODUCTS);
    }

    private CbsProducts(Name alias, Table<CbsProductsRecord> aliased) {
        this(alias, aliased, null);
    }

    private CbsProducts(Name alias, Table<CbsProductsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> CbsProducts(Table<O> child, ForeignKey<O, CbsProductsRecord> key) {
        super(child, key, CBS_PRODUCTS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return App.APP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CbsProductsRecord> getPrimaryKey() {
        return Keys.CBS_PRODUCTS_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CbsProductsRecord>> getKeys() {
        return Arrays.<UniqueKey<CbsProductsRecord>>asList(Keys.CBS_PRODUCTS_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsProducts as(String alias) {
        return new CbsProducts(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsProducts as(Name alias) {
        return new CbsProducts(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CbsProducts rename(String name) {
        return new CbsProducts(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CbsProducts rename(Name name) {
        return new CbsProducts(name, null);
    }
}
