/*
 * This file is generated by jOOQ.
 */
package tjcbs.jooq.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import tjcbs.jooq.db.App;
import tjcbs.jooq.db.Keys;
import tjcbs.jooq.db.tables.records.CbsSavingsTransactionsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CbsSavingsTransactions extends TableImpl<CbsSavingsTransactionsRecord> {

    private static final long serialVersionUID = 1540343775;

    /**
     * The reference instance of <code>APP.CBS_SAVINGS_TRANSACTIONS</code>
     */
    public static final CbsSavingsTransactions CBS_SAVINGS_TRANSACTIONS = new CbsSavingsTransactions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CbsSavingsTransactionsRecord> getRecordType() {
        return CbsSavingsTransactionsRecord.class;
    }

    /**
     * The column <code>APP.CBS_SAVINGS_TRANSACTIONS.ID</code>.
     */
    public final TableField<CbsSavingsTransactionsRecord, String> ID = createField("ID", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>APP.CBS_SAVINGS_TRANSACTIONS.NINO</code>.
     */
    public final TableField<CbsSavingsTransactionsRecord, String> NINO = createField("NINO", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>APP.CBS_SAVINGS_TRANSACTIONS.TXID</code>.
     */
    public final TableField<CbsSavingsTransactionsRecord, String> TXID = createField("TXID", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>APP.CBS_SAVINGS_TRANSACTIONS.LABEL</code>.
     */
    public final TableField<CbsSavingsTransactionsRecord, String> LABEL = createField("LABEL", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>APP.CBS_SAVINGS_TRANSACTIONS.TDATE</code>.
     */
    public final TableField<CbsSavingsTransactionsRecord, Integer> TDATE = createField("TDATE", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>APP.CBS_SAVINGS_TRANSACTIONS.TTIME</code>.
     */
    public final TableField<CbsSavingsTransactionsRecord, Integer> TTIME = createField("TTIME", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>APP.CBS_SAVINGS_TRANSACTIONS.AMOUNT</code>.
     */
    public final TableField<CbsSavingsTransactionsRecord, Double> AMOUNT = createField("AMOUNT", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * Create a <code>APP.CBS_SAVINGS_TRANSACTIONS</code> table reference
     */
    public CbsSavingsTransactions() {
        this(DSL.name("CBS_SAVINGS_TRANSACTIONS"), null);
    }

    /**
     * Create an aliased <code>APP.CBS_SAVINGS_TRANSACTIONS</code> table reference
     */
    public CbsSavingsTransactions(String alias) {
        this(DSL.name(alias), CBS_SAVINGS_TRANSACTIONS);
    }

    /**
     * Create an aliased <code>APP.CBS_SAVINGS_TRANSACTIONS</code> table reference
     */
    public CbsSavingsTransactions(Name alias) {
        this(alias, CBS_SAVINGS_TRANSACTIONS);
    }

    private CbsSavingsTransactions(Name alias, Table<CbsSavingsTransactionsRecord> aliased) {
        this(alias, aliased, null);
    }

    private CbsSavingsTransactions(Name alias, Table<CbsSavingsTransactionsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> CbsSavingsTransactions(Table<O> child, ForeignKey<O, CbsSavingsTransactionsRecord> key) {
        super(child, key, CBS_SAVINGS_TRANSACTIONS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return App.APP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CbsSavingsTransactionsRecord> getPrimaryKey() {
        return Keys.CBS_SAVINGS_TRANSACTIONS_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CbsSavingsTransactionsRecord>> getKeys() {
        return Arrays.<UniqueKey<CbsSavingsTransactionsRecord>>asList(Keys.CBS_SAVINGS_TRANSACTIONS_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<CbsSavingsTransactionsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CbsSavingsTransactionsRecord, ?>>asList(Keys.SQL181029115214420);
    }

    public CbsSavingsAccount cbsSavingsAccount() {
        return new CbsSavingsAccount(this, Keys.SQL181029115214420);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSavingsTransactions as(String alias) {
        return new CbsSavingsTransactions(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSavingsTransactions as(Name alias) {
        return new CbsSavingsTransactions(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CbsSavingsTransactions rename(String name) {
        return new CbsSavingsTransactions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CbsSavingsTransactions rename(Name name) {
        return new CbsSavingsTransactions(name, null);
    }
}
