/*
 * This file is generated by jOOQ.
 */
package tjcbs.jooq.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import tjcbs.jooq.db.App;
import tjcbs.jooq.db.Keys;
import tjcbs.jooq.db.tables.records.CbsSavingsAccountLimitRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CbsSavingsAccountLimit extends TableImpl<CbsSavingsAccountLimitRecord> {

    private static final long serialVersionUID = -22359247;

    /**
     * The reference instance of <code>APP.CBS_SAVINGS_ACCOUNT_LIMIT</code>
     */
    public static final CbsSavingsAccountLimit CBS_SAVINGS_ACCOUNT_LIMIT = new CbsSavingsAccountLimit();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CbsSavingsAccountLimitRecord> getRecordType() {
        return CbsSavingsAccountLimitRecord.class;
    }

    /**
     * The column <code>APP.CBS_SAVINGS_ACCOUNT_LIMIT.ID</code>.
     */
    public final TableField<CbsSavingsAccountLimitRecord, String> ID = createField("ID", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>APP.CBS_SAVINGS_ACCOUNT_LIMIT.NINO</code>.
     */
    public final TableField<CbsSavingsAccountLimitRecord, String> NINO = createField("NINO", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>APP.CBS_SAVINGS_ACCOUNT_LIMIT.MAXIMUM_OVERDRAFT</code>.
     */
    public final TableField<CbsSavingsAccountLimitRecord, Integer> MAXIMUM_OVERDRAFT = createField("MAXIMUM_OVERDRAFT", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>APP.CBS_SAVINGS_ACCOUNT_LIMIT</code> table reference
     */
    public CbsSavingsAccountLimit() {
        this(DSL.name("CBS_SAVINGS_ACCOUNT_LIMIT"), null);
    }

    /**
     * Create an aliased <code>APP.CBS_SAVINGS_ACCOUNT_LIMIT</code> table reference
     */
    public CbsSavingsAccountLimit(String alias) {
        this(DSL.name(alias), CBS_SAVINGS_ACCOUNT_LIMIT);
    }

    /**
     * Create an aliased <code>APP.CBS_SAVINGS_ACCOUNT_LIMIT</code> table reference
     */
    public CbsSavingsAccountLimit(Name alias) {
        this(alias, CBS_SAVINGS_ACCOUNT_LIMIT);
    }

    private CbsSavingsAccountLimit(Name alias, Table<CbsSavingsAccountLimitRecord> aliased) {
        this(alias, aliased, null);
    }

    private CbsSavingsAccountLimit(Name alias, Table<CbsSavingsAccountLimitRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> CbsSavingsAccountLimit(Table<O> child, ForeignKey<O, CbsSavingsAccountLimitRecord> key) {
        super(child, key, CBS_SAVINGS_ACCOUNT_LIMIT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return App.APP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CbsSavingsAccountLimitRecord> getPrimaryKey() {
        return Keys.CBS_SAVINGS_ACCOUNT_LIMIT_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CbsSavingsAccountLimitRecord>> getKeys() {
        return Arrays.<UniqueKey<CbsSavingsAccountLimitRecord>>asList(Keys.CBS_SAVINGS_ACCOUNT_LIMIT_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<CbsSavingsAccountLimitRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CbsSavingsAccountLimitRecord, ?>>asList(Keys.SQL181029115214460);
    }

    public CbsCustomer cbsCustomer() {
        return new CbsCustomer(this, Keys.SQL181029115214460);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSavingsAccountLimit as(String alias) {
        return new CbsSavingsAccountLimit(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSavingsAccountLimit as(Name alias) {
        return new CbsSavingsAccountLimit(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CbsSavingsAccountLimit rename(String name) {
        return new CbsSavingsAccountLimit(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CbsSavingsAccountLimit rename(Name name) {
        return new CbsSavingsAccountLimit(name, null);
    }
}
