/*
 * This file is generated by jOOQ.
 */
package tjcbs.jooq.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import tjcbs.jooq.db.App;
import tjcbs.jooq.db.Keys;
import tjcbs.jooq.db.tables.records.CbsSavingsAccountRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CbsSavingsAccount extends TableImpl<CbsSavingsAccountRecord> {

    private static final long serialVersionUID = -556113063;

    /**
     * The reference instance of <code>APP.CBS_SAVINGS_ACCOUNT</code>
     */
    public static final CbsSavingsAccount CBS_SAVINGS_ACCOUNT = new CbsSavingsAccount();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CbsSavingsAccountRecord> getRecordType() {
        return CbsSavingsAccountRecord.class;
    }

    /**
     * The column <code>APP.CBS_SAVINGS_ACCOUNT.ID</code>.
     */
    public final TableField<CbsSavingsAccountRecord, String> ID = createField("ID", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>APP.CBS_SAVINGS_ACCOUNT.NINO</code>.
     */
    public final TableField<CbsSavingsAccountRecord, String> NINO = createField("NINO", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>APP.CBS_SAVINGS_ACCOUNT.NAME</code>.
     */
    public final TableField<CbsSavingsAccountRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>APP.CBS_SAVINGS_ACCOUNT.CCY</code>.
     */
    public final TableField<CbsSavingsAccountRecord, String> CCY = createField("CCY", org.jooq.impl.SQLDataType.VARCHAR(3).nullable(false), this, "");

    /**
     * The column <code>APP.CBS_SAVINGS_ACCOUNT.BALANCE</code>.
     */
    public final TableField<CbsSavingsAccountRecord, Double> BALANCE = createField("BALANCE", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>APP.CBS_SAVINGS_ACCOUNT.INTEREST</code>.
     */
    public final TableField<CbsSavingsAccountRecord, Double> INTEREST = createField("INTEREST", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * Create a <code>APP.CBS_SAVINGS_ACCOUNT</code> table reference
     */
    public CbsSavingsAccount() {
        this(DSL.name("CBS_SAVINGS_ACCOUNT"), null);
    }

    /**
     * Create an aliased <code>APP.CBS_SAVINGS_ACCOUNT</code> table reference
     */
    public CbsSavingsAccount(String alias) {
        this(DSL.name(alias), CBS_SAVINGS_ACCOUNT);
    }

    /**
     * Create an aliased <code>APP.CBS_SAVINGS_ACCOUNT</code> table reference
     */
    public CbsSavingsAccount(Name alias) {
        this(alias, CBS_SAVINGS_ACCOUNT);
    }

    private CbsSavingsAccount(Name alias, Table<CbsSavingsAccountRecord> aliased) {
        this(alias, aliased, null);
    }

    private CbsSavingsAccount(Name alias, Table<CbsSavingsAccountRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> CbsSavingsAccount(Table<O> child, ForeignKey<O, CbsSavingsAccountRecord> key) {
        super(child, key, CBS_SAVINGS_ACCOUNT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return App.APP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CbsSavingsAccountRecord> getPrimaryKey() {
        return Keys.CBS_SAVINGS_ACCOUNT_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CbsSavingsAccountRecord>> getKeys() {
        return Arrays.<UniqueKey<CbsSavingsAccountRecord>>asList(Keys.CBS_SAVINGS_ACCOUNT_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<CbsSavingsAccountRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CbsSavingsAccountRecord, ?>>asList(Keys.SQL181029115214370);
    }

    public CbsCustomer cbsCustomer() {
        return new CbsCustomer(this, Keys.SQL181029115214370);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSavingsAccount as(String alias) {
        return new CbsSavingsAccount(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSavingsAccount as(Name alias) {
        return new CbsSavingsAccount(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CbsSavingsAccount rename(String name) {
        return new CbsSavingsAccount(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CbsSavingsAccount rename(Name name) {
        return new CbsSavingsAccount(name, null);
    }
}
