/*
 * This file is generated by jOOQ.
 */
package tjcbs.jooq.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import tjcbs.jooq.db.App;
import tjcbs.jooq.db.Keys;
import tjcbs.jooq.db.tables.records.CbsSimpleLoanPaymentScheduleRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CbsSimpleLoanPaymentSchedule extends TableImpl<CbsSimpleLoanPaymentScheduleRecord> {

    private static final long serialVersionUID = 882890806;

    /**
     * The reference instance of <code>APP.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE</code>
     */
    public static final CbsSimpleLoanPaymentSchedule CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE = new CbsSimpleLoanPaymentSchedule();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CbsSimpleLoanPaymentScheduleRecord> getRecordType() {
        return CbsSimpleLoanPaymentScheduleRecord.class;
    }

    /**
     * The column <code>APP.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.ID</code>.
     */
    public final TableField<CbsSimpleLoanPaymentScheduleRecord, String> ID = createField("ID", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>APP.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.LOAN_ID</code>.
     */
    public final TableField<CbsSimpleLoanPaymentScheduleRecord, String> LOAN_ID = createField("LOAN_ID", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>APP.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.NINO</code>.
     */
    public final TableField<CbsSimpleLoanPaymentScheduleRecord, String> NINO = createField("NINO", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>APP.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.CASA_ID</code>.
     */
    public final TableField<CbsSimpleLoanPaymentScheduleRecord, String> CASA_ID = createField("CASA_ID", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>APP.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.AMOUNT_DUE</code>.
     */
    public final TableField<CbsSimpleLoanPaymentScheduleRecord, Double> AMOUNT_DUE = createField("AMOUNT_DUE", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>APP.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.PRINCIPAL_DUE</code>.
     */
    public final TableField<CbsSimpleLoanPaymentScheduleRecord, Double> PRINCIPAL_DUE = createField("PRINCIPAL_DUE", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>APP.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.INTEREST_DUE</code>.
     */
    public final TableField<CbsSimpleLoanPaymentScheduleRecord, Double> INTEREST_DUE = createField("INTEREST_DUE", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>APP.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.AT_DATE</code>.
     */
    public final TableField<CbsSimpleLoanPaymentScheduleRecord, Integer> AT_DATE = createField("AT_DATE", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>APP.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.STATUS</code>.
     */
    public final TableField<CbsSimpleLoanPaymentScheduleRecord, String> STATUS = createField("STATUS", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * Create a <code>APP.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE</code> table reference
     */
    public CbsSimpleLoanPaymentSchedule() {
        this(DSL.name("CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE"), null);
    }

    /**
     * Create an aliased <code>APP.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE</code> table reference
     */
    public CbsSimpleLoanPaymentSchedule(String alias) {
        this(DSL.name(alias), CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE);
    }

    /**
     * Create an aliased <code>APP.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE</code> table reference
     */
    public CbsSimpleLoanPaymentSchedule(Name alias) {
        this(alias, CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE);
    }

    private CbsSimpleLoanPaymentSchedule(Name alias, Table<CbsSimpleLoanPaymentScheduleRecord> aliased) {
        this(alias, aliased, null);
    }

    private CbsSimpleLoanPaymentSchedule(Name alias, Table<CbsSimpleLoanPaymentScheduleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> CbsSimpleLoanPaymentSchedule(Table<O> child, ForeignKey<O, CbsSimpleLoanPaymentScheduleRecord> key) {
        super(child, key, CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return App.APP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CbsSimpleLoanPaymentScheduleRecord> getPrimaryKey() {
        return Keys.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CbsSimpleLoanPaymentScheduleRecord>> getKeys() {
        return Arrays.<UniqueKey<CbsSimpleLoanPaymentScheduleRecord>>asList(Keys.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<CbsSimpleLoanPaymentScheduleRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CbsSimpleLoanPaymentScheduleRecord, ?>>asList(Keys.SQL181029115214640);
    }

    public CbsSimpleLoan cbsSimpleLoan() {
        return new CbsSimpleLoan(this, Keys.SQL181029115214640);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSimpleLoanPaymentSchedule as(String alias) {
        return new CbsSimpleLoanPaymentSchedule(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSimpleLoanPaymentSchedule as(Name alias) {
        return new CbsSimpleLoanPaymentSchedule(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CbsSimpleLoanPaymentSchedule rename(String name) {
        return new CbsSimpleLoanPaymentSchedule(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CbsSimpleLoanPaymentSchedule rename(Name name) {
        return new CbsSimpleLoanPaymentSchedule(name, null);
    }
}
