/*
 * This file is generated by jOOQ.
 */
package tjcbs.jooq.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CbsAccount implements Serializable {

    private static final long serialVersionUID = 272957723;

    private String id;
    private Double allocatedAmount;
    private Double currentAmount;

    public CbsAccount() {}

    public CbsAccount(CbsAccount value) {
        this.id = value.id;
        this.allocatedAmount = value.allocatedAmount;
        this.currentAmount = value.currentAmount;
    }

    public CbsAccount(
        String id,
        Double allocatedAmount,
        Double currentAmount
    ) {
        this.id = id;
        this.allocatedAmount = allocatedAmount;
        this.currentAmount = currentAmount;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Double getAllocatedAmount() {
        return this.allocatedAmount;
    }

    public void setAllocatedAmount(Double allocatedAmount) {
        this.allocatedAmount = allocatedAmount;
    }

    public Double getCurrentAmount() {
        return this.currentAmount;
    }

    public void setCurrentAmount(Double currentAmount) {
        this.currentAmount = currentAmount;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CbsAccount (");

        sb.append(id);
        sb.append(", ").append(allocatedAmount);
        sb.append(", ").append(currentAmount);

        sb.append(")");
        return sb.toString();
    }
}
