/*
 * This file is generated by jOOQ.
 */
package tjcbs.jooq.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CbsCustomerEmails implements Serializable {

    private static final long serialVersionUID = 310978350;

    private String nino;
    private String email;

    public CbsCustomerEmails() {}

    public CbsCustomerEmails(CbsCustomerEmails value) {
        this.nino = value.nino;
        this.email = value.email;
    }

    public CbsCustomerEmails(
        String nino,
        String email
    ) {
        this.nino = nino;
        this.email = email;
    }

    public String getNino() {
        return this.nino;
    }

    public void setNino(String nino) {
        this.nino = nino;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CbsCustomerEmails (");

        sb.append(nino);
        sb.append(", ").append(email);

        sb.append(")");
        return sb.toString();
    }
}
