/*
 * This file is generated by jOOQ.
 */
package tjcbs.jooq.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CbsCustomerAddress implements Serializable {

    private static final long serialVersionUID = 943770207;

    private String nino;
    private String addressLine_1;
    private String addressLine_2;
    private String addressLine_3;
    private String city;
    private String province;
    private String postcode;
    private String country;

    public CbsCustomerAddress() {}

    public CbsCustomerAddress(CbsCustomerAddress value) {
        this.nino = value.nino;
        this.addressLine_1 = value.addressLine_1;
        this.addressLine_2 = value.addressLine_2;
        this.addressLine_3 = value.addressLine_3;
        this.city = value.city;
        this.province = value.province;
        this.postcode = value.postcode;
        this.country = value.country;
    }

    public CbsCustomerAddress(
        String nino,
        String addressLine_1,
        String addressLine_2,
        String addressLine_3,
        String city,
        String province,
        String postcode,
        String country
    ) {
        this.nino = nino;
        this.addressLine_1 = addressLine_1;
        this.addressLine_2 = addressLine_2;
        this.addressLine_3 = addressLine_3;
        this.city = city;
        this.province = province;
        this.postcode = postcode;
        this.country = country;
    }

    public String getNino() {
        return this.nino;
    }

    public void setNino(String nino) {
        this.nino = nino;
    }

    public String getAddressLine_1() {
        return this.addressLine_1;
    }

    public void setAddressLine_1(String addressLine_1) {
        this.addressLine_1 = addressLine_1;
    }

    public String getAddressLine_2() {
        return this.addressLine_2;
    }

    public void setAddressLine_2(String addressLine_2) {
        this.addressLine_2 = addressLine_2;
    }

    public String getAddressLine_3() {
        return this.addressLine_3;
    }

    public void setAddressLine_3(String addressLine_3) {
        this.addressLine_3 = addressLine_3;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getProvince() {
        return this.province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getPostcode() {
        return this.postcode;
    }

    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CbsCustomerAddress (");

        sb.append(nino);
        sb.append(", ").append(addressLine_1);
        sb.append(", ").append(addressLine_2);
        sb.append(", ").append(addressLine_3);
        sb.append(", ").append(city);
        sb.append(", ").append(province);
        sb.append(", ").append(postcode);
        sb.append(", ").append(country);

        sb.append(")");
        return sb.toString();
    }
}
