/*
 * This file is generated by jOOQ.
 */
package tjcbs.jooq.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CbsCustomer implements Serializable {

    private static final long serialVersionUID = 992009757;

    private String  nino;
    private String  firstName;
    private String  lastName;
    private Integer dob;
    private String  primaryEmail;

    public CbsCustomer() {}

    public CbsCustomer(CbsCustomer value) {
        this.nino = value.nino;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.dob = value.dob;
        this.primaryEmail = value.primaryEmail;
    }

    public CbsCustomer(
        String  nino,
        String  firstName,
        String  lastName,
        Integer dob,
        String  primaryEmail
    ) {
        this.nino = nino;
        this.firstName = firstName;
        this.lastName = lastName;
        this.dob = dob;
        this.primaryEmail = primaryEmail;
    }

    public String getNino() {
        return this.nino;
    }

    public void setNino(String nino) {
        this.nino = nino;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public Integer getDob() {
        return this.dob;
    }

    public void setDob(Integer dob) {
        this.dob = dob;
    }

    public String getPrimaryEmail() {
        return this.primaryEmail;
    }

    public void setPrimaryEmail(String primaryEmail) {
        this.primaryEmail = primaryEmail;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CbsCustomer (");

        sb.append(nino);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(dob);
        sb.append(", ").append(primaryEmail);

        sb.append(")");
        return sb.toString();
    }
}
