/*
 * This file is generated by jOOQ.
 */
package tjcbs.jooq.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CbsProducts implements Serializable {

    private static final long serialVersionUID = -671750496;

    private String partnerId;
    private String product;

    public CbsProducts() {}

    public CbsProducts(CbsProducts value) {
        this.partnerId = value.partnerId;
        this.product = value.product;
    }

    public CbsProducts(
        String partnerId,
        String product
    ) {
        this.partnerId = partnerId;
        this.product = product;
    }

    public String getPartnerId() {
        return this.partnerId;
    }

    public void setPartnerId(String partnerId) {
        this.partnerId = partnerId;
    }

    public String getProduct() {
        return this.product;
    }

    public void setProduct(String product) {
        this.product = product;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CbsProducts (");

        sb.append(partnerId);
        sb.append(", ").append(product);

        sb.append(")");
        return sb.toString();
    }
}
