/*
 * This file is generated by jOOQ.
 */
package tjcbs.jooq.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CbsSimpleLoanPaymentSchedule implements Serializable {

    private static final long serialVersionUID = 1316271932;

    private String  id;
    private String  loanId;
    private String  nino;
    private String  casaId;
    private Double  amountDue;
    private Double  principalDue;
    private Double  interestDue;
    private Integer atDate;
    private String  status;

    public CbsSimpleLoanPaymentSchedule() {}

    public CbsSimpleLoanPaymentSchedule(CbsSimpleLoanPaymentSchedule value) {
        this.id = value.id;
        this.loanId = value.loanId;
        this.nino = value.nino;
        this.casaId = value.casaId;
        this.amountDue = value.amountDue;
        this.principalDue = value.principalDue;
        this.interestDue = value.interestDue;
        this.atDate = value.atDate;
        this.status = value.status;
    }

    public CbsSimpleLoanPaymentSchedule(
        String  id,
        String  loanId,
        String  nino,
        String  casaId,
        Double  amountDue,
        Double  principalDue,
        Double  interestDue,
        Integer atDate,
        String  status
    ) {
        this.id = id;
        this.loanId = loanId;
        this.nino = nino;
        this.casaId = casaId;
        this.amountDue = amountDue;
        this.principalDue = principalDue;
        this.interestDue = interestDue;
        this.atDate = atDate;
        this.status = status;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getLoanId() {
        return this.loanId;
    }

    public void setLoanId(String loanId) {
        this.loanId = loanId;
    }

    public String getNino() {
        return this.nino;
    }

    public void setNino(String nino) {
        this.nino = nino;
    }

    public String getCasaId() {
        return this.casaId;
    }

    public void setCasaId(String casaId) {
        this.casaId = casaId;
    }

    public Double getAmountDue() {
        return this.amountDue;
    }

    public void setAmountDue(Double amountDue) {
        this.amountDue = amountDue;
    }

    public Double getPrincipalDue() {
        return this.principalDue;
    }

    public void setPrincipalDue(Double principalDue) {
        this.principalDue = principalDue;
    }

    public Double getInterestDue() {
        return this.interestDue;
    }

    public void setInterestDue(Double interestDue) {
        this.interestDue = interestDue;
    }

    public Integer getAtDate() {
        return this.atDate;
    }

    public void setAtDate(Integer atDate) {
        this.atDate = atDate;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CbsSimpleLoanPaymentSchedule (");

        sb.append(id);
        sb.append(", ").append(loanId);
        sb.append(", ").append(nino);
        sb.append(", ").append(casaId);
        sb.append(", ").append(amountDue);
        sb.append(", ").append(principalDue);
        sb.append(", ").append(interestDue);
        sb.append(", ").append(atDate);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
