/*
 * This file is generated by jOOQ.
 */
package tjcbs.jooq.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CbsSimpleLoan implements Serializable {

    private static final long serialVersionUID = 1707194041;

    private String  id;
    private String  nino;
    private String  casaId;
    private Integer fromDate;
    private Integer toDate;
    private Double  principal;
    private Double  interest;
    private Integer installments;
    private String  paymentDue;
    private String  status;

    public CbsSimpleLoan() {}

    public CbsSimpleLoan(CbsSimpleLoan value) {
        this.id = value.id;
        this.nino = value.nino;
        this.casaId = value.casaId;
        this.fromDate = value.fromDate;
        this.toDate = value.toDate;
        this.principal = value.principal;
        this.interest = value.interest;
        this.installments = value.installments;
        this.paymentDue = value.paymentDue;
        this.status = value.status;
    }

    public CbsSimpleLoan(
        String  id,
        String  nino,
        String  casaId,
        Integer fromDate,
        Integer toDate,
        Double  principal,
        Double  interest,
        Integer installments,
        String  paymentDue,
        String  status
    ) {
        this.id = id;
        this.nino = nino;
        this.casaId = casaId;
        this.fromDate = fromDate;
        this.toDate = toDate;
        this.principal = principal;
        this.interest = interest;
        this.installments = installments;
        this.paymentDue = paymentDue;
        this.status = status;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getNino() {
        return this.nino;
    }

    public void setNino(String nino) {
        this.nino = nino;
    }

    public String getCasaId() {
        return this.casaId;
    }

    public void setCasaId(String casaId) {
        this.casaId = casaId;
    }

    public Integer getFromDate() {
        return this.fromDate;
    }

    public void setFromDate(Integer fromDate) {
        this.fromDate = fromDate;
    }

    public Integer getToDate() {
        return this.toDate;
    }

    public void setToDate(Integer toDate) {
        this.toDate = toDate;
    }

    public Double getPrincipal() {
        return this.principal;
    }

    public void setPrincipal(Double principal) {
        this.principal = principal;
    }

    public Double getInterest() {
        return this.interest;
    }

    public void setInterest(Double interest) {
        this.interest = interest;
    }

    public Integer getInstallments() {
        return this.installments;
    }

    public void setInstallments(Integer installments) {
        this.installments = installments;
    }

    public String getPaymentDue() {
        return this.paymentDue;
    }

    public void setPaymentDue(String paymentDue) {
        this.paymentDue = paymentDue;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CbsSimpleLoan (");

        sb.append(id);
        sb.append(", ").append(nino);
        sb.append(", ").append(casaId);
        sb.append(", ").append(fromDate);
        sb.append(", ").append(toDate);
        sb.append(", ").append(principal);
        sb.append(", ").append(interest);
        sb.append(", ").append(installments);
        sb.append(", ").append(paymentDue);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
