/*
 * This file is generated by jOOQ.
 */
package tjcbs.jooq.db.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import tjcbs.jooq.db.tables.CbsAccount;
import tjcbs.jooq.db.tables.records.CbsAccountRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CbsAccountDao extends DAOImpl<CbsAccountRecord, tjcbs.jooq.db.tables.pojos.CbsAccount, String> {

    /**
     * Create a new CbsAccountDao without any configuration
     */
    public CbsAccountDao() {
        super(CbsAccount.CBS_ACCOUNT, tjcbs.jooq.db.tables.pojos.CbsAccount.class);
    }

    /**
     * Create a new CbsAccountDao with an attached configuration
     */
    public CbsAccountDao(Configuration configuration) {
        super(CbsAccount.CBS_ACCOUNT, tjcbs.jooq.db.tables.pojos.CbsAccount.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(tjcbs.jooq.db.tables.pojos.CbsAccount object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<tjcbs.jooq.db.tables.pojos.CbsAccount> fetchById(String... values) {
        return fetch(CbsAccount.CBS_ACCOUNT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public tjcbs.jooq.db.tables.pojos.CbsAccount fetchOneById(String value) {
        return fetchOne(CbsAccount.CBS_ACCOUNT.ID, value);
    }

    /**
     * Fetch records that have <code>ALLOCATED_AMOUNT IN (values)</code>
     */
    public List<tjcbs.jooq.db.tables.pojos.CbsAccount> fetchByAllocatedAmount(Double... values) {
        return fetch(CbsAccount.CBS_ACCOUNT.ALLOCATED_AMOUNT, values);
    }

    /**
     * Fetch records that have <code>CURRENT_AMOUNT IN (values)</code>
     */
    public List<tjcbs.jooq.db.tables.pojos.CbsAccount> fetchByCurrentAmount(Double... values) {
        return fetch(CbsAccount.CBS_ACCOUNT.CURRENT_AMOUNT, values);
    }
}
