/*
 * This file is generated by jOOQ.
 */
package tjcbs.jooq.db.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import tjcbs.jooq.db.tables.CbsCustomer;
import tjcbs.jooq.db.tables.records.CbsCustomerRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CbsCustomerDao extends DAOImpl<CbsCustomerRecord, tjcbs.jooq.db.tables.pojos.CbsCustomer, String> {

    /**
     * Create a new CbsCustomerDao without any configuration
     */
    public CbsCustomerDao() {
        super(CbsCustomer.CBS_CUSTOMER, tjcbs.jooq.db.tables.pojos.CbsCustomer.class);
    }

    /**
     * Create a new CbsCustomerDao with an attached configuration
     */
    public CbsCustomerDao(Configuration configuration) {
        super(CbsCustomer.CBS_CUSTOMER, tjcbs.jooq.db.tables.pojos.CbsCustomer.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(tjcbs.jooq.db.tables.pojos.CbsCustomer object) {
        return object.getNino();
    }

    /**
     * Fetch records that have <code>NINO IN (values)</code>
     */
    public List<tjcbs.jooq.db.tables.pojos.CbsCustomer> fetchByNino(String... values) {
        return fetch(CbsCustomer.CBS_CUSTOMER.NINO, values);
    }

    /**
     * Fetch a unique record that has <code>NINO = value</code>
     */
    public tjcbs.jooq.db.tables.pojos.CbsCustomer fetchOneByNino(String value) {
        return fetchOne(CbsCustomer.CBS_CUSTOMER.NINO, value);
    }

    /**
     * Fetch records that have <code>FIRST_NAME IN (values)</code>
     */
    public List<tjcbs.jooq.db.tables.pojos.CbsCustomer> fetchByFirstName(String... values) {
        return fetch(CbsCustomer.CBS_CUSTOMER.FIRST_NAME, values);
    }

    /**
     * Fetch records that have <code>LAST_NAME IN (values)</code>
     */
    public List<tjcbs.jooq.db.tables.pojos.CbsCustomer> fetchByLastName(String... values) {
        return fetch(CbsCustomer.CBS_CUSTOMER.LAST_NAME, values);
    }

    /**
     * Fetch records that have <code>DOB IN (values)</code>
     */
    public List<tjcbs.jooq.db.tables.pojos.CbsCustomer> fetchByDob(Integer... values) {
        return fetch(CbsCustomer.CBS_CUSTOMER.DOB, values);
    }

    /**
     * Fetch records that have <code>PRIMARY_EMAIL IN (values)</code>
     */
    public List<tjcbs.jooq.db.tables.pojos.CbsCustomer> fetchByPrimaryEmail(String... values) {
        return fetch(CbsCustomer.CBS_CUSTOMER.PRIMARY_EMAIL, values);
    }
}
