/*
 * This file is generated by jOOQ.
 */
package tjcbs.jooq.db.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;

import tjcbs.jooq.db.tables.CbsCreditAccountLimit;
import tjcbs.jooq.db.tables.records.CbsCreditAccountLimitRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CbsCreditAccountLimitDao extends DAOImpl<CbsCreditAccountLimitRecord, tjcbs.jooq.db.tables.pojos.CbsCreditAccountLimit, Record2<String, String>> {

    /**
     * Create a new CbsCreditAccountLimitDao without any configuration
     */
    public CbsCreditAccountLimitDao() {
        super(CbsCreditAccountLimit.CBS_CREDIT_ACCOUNT_LIMIT, tjcbs.jooq.db.tables.pojos.CbsCreditAccountLimit.class);
    }

    /**
     * Create a new CbsCreditAccountLimitDao with an attached configuration
     */
    public CbsCreditAccountLimitDao(Configuration configuration) {
        super(CbsCreditAccountLimit.CBS_CREDIT_ACCOUNT_LIMIT, tjcbs.jooq.db.tables.pojos.CbsCreditAccountLimit.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<String, String> getId(tjcbs.jooq.db.tables.pojos.CbsCreditAccountLimit object) {
        return compositeKeyRecord(object.getId(), object.getNino());
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<tjcbs.jooq.db.tables.pojos.CbsCreditAccountLimit> fetchById(String... values) {
        return fetch(CbsCreditAccountLimit.CBS_CREDIT_ACCOUNT_LIMIT.ID, values);
    }

    /**
     * Fetch records that have <code>NINO IN (values)</code>
     */
    public List<tjcbs.jooq.db.tables.pojos.CbsCreditAccountLimit> fetchByNino(String... values) {
        return fetch(CbsCreditAccountLimit.CBS_CREDIT_ACCOUNT_LIMIT.NINO, values);
    }

    /**
     * Fetch records that have <code>MAXIMUM_OVERDRAFT IN (values)</code>
     */
    public List<tjcbs.jooq.db.tables.pojos.CbsCreditAccountLimit> fetchByMaximumOverdraft(Integer... values) {
        return fetch(CbsCreditAccountLimit.CBS_CREDIT_ACCOUNT_LIMIT.MAXIMUM_OVERDRAFT, values);
    }
}
