/*
 * This file is generated by jOOQ.
 */
package tjcbs.jooq.db.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;

import tjcbs.jooq.db.tables.CbsCreditAccount;
import tjcbs.jooq.db.tables.records.CbsCreditAccountRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CbsCreditAccountDao extends DAOImpl<CbsCreditAccountRecord, tjcbs.jooq.db.tables.pojos.CbsCreditAccount, Record2<String, String>> {

    /**
     * Create a new CbsCreditAccountDao without any configuration
     */
    public CbsCreditAccountDao() {
        super(CbsCreditAccount.CBS_CREDIT_ACCOUNT, tjcbs.jooq.db.tables.pojos.CbsCreditAccount.class);
    }

    /**
     * Create a new CbsCreditAccountDao with an attached configuration
     */
    public CbsCreditAccountDao(Configuration configuration) {
        super(CbsCreditAccount.CBS_CREDIT_ACCOUNT, tjcbs.jooq.db.tables.pojos.CbsCreditAccount.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<String, String> getId(tjcbs.jooq.db.tables.pojos.CbsCreditAccount object) {
        return compositeKeyRecord(object.getId(), object.getNino());
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<tjcbs.jooq.db.tables.pojos.CbsCreditAccount> fetchById(String... values) {
        return fetch(CbsCreditAccount.CBS_CREDIT_ACCOUNT.ID, values);
    }

    /**
     * Fetch records that have <code>NINO IN (values)</code>
     */
    public List<tjcbs.jooq.db.tables.pojos.CbsCreditAccount> fetchByNino(String... values) {
        return fetch(CbsCreditAccount.CBS_CREDIT_ACCOUNT.NINO, values);
    }

    /**
     * Fetch records that have <code>NAME IN (values)</code>
     */
    public List<tjcbs.jooq.db.tables.pojos.CbsCreditAccount> fetchByName(String... values) {
        return fetch(CbsCreditAccount.CBS_CREDIT_ACCOUNT.NAME, values);
    }

    /**
     * Fetch records that have <code>LABEL IN (values)</code>
     */
    public List<tjcbs.jooq.db.tables.pojos.CbsCreditAccount> fetchByLabel(String... values) {
        return fetch(CbsCreditAccount.CBS_CREDIT_ACCOUNT.LABEL, values);
    }

    /**
     * Fetch records that have <code>TDATE IN (values)</code>
     */
    public List<tjcbs.jooq.db.tables.pojos.CbsCreditAccount> fetchByTdate(Integer... values) {
        return fetch(CbsCreditAccount.CBS_CREDIT_ACCOUNT.TDATE, values);
    }

    /**
     * Fetch records that have <code>TTIME IN (values)</code>
     */
    public List<tjcbs.jooq.db.tables.pojos.CbsCreditAccount> fetchByTtime(Integer... values) {
        return fetch(CbsCreditAccount.CBS_CREDIT_ACCOUNT.TTIME, values);
    }

    /**
     * Fetch records that have <code>AMOUNT IN (values)</code>
     */
    public List<tjcbs.jooq.db.tables.pojos.CbsCreditAccount> fetchByAmount(Double... values) {
        return fetch(CbsCreditAccount.CBS_CREDIT_ACCOUNT.AMOUNT, values);
    }
}
