/*
 * This file is generated by jOOQ.
 */
package tjcbs.jooq.db.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import tjcbs.jooq.db.tables.CbsInfo;
import tjcbs.jooq.db.tables.records.CbsInfoRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CbsInfoDao extends DAOImpl<CbsInfoRecord, tjcbs.jooq.db.tables.pojos.CbsInfo, String> {

    /**
     * Create a new CbsInfoDao without any configuration
     */
    public CbsInfoDao() {
        super(CbsInfo.CBS_INFO, tjcbs.jooq.db.tables.pojos.CbsInfo.class);
    }

    /**
     * Create a new CbsInfoDao with an attached configuration
     */
    public CbsInfoDao(Configuration configuration) {
        super(CbsInfo.CBS_INFO, tjcbs.jooq.db.tables.pojos.CbsInfo.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(tjcbs.jooq.db.tables.pojos.CbsInfo object) {
        return object.getPartnerId();
    }

    /**
     * Fetch records that have <code>PARTNER_ID IN (values)</code>
     */
    public List<tjcbs.jooq.db.tables.pojos.CbsInfo> fetchByPartnerId(String... values) {
        return fetch(CbsInfo.CBS_INFO.PARTNER_ID, values);
    }

    /**
     * Fetch a unique record that has <code>PARTNER_ID = value</code>
     */
    public tjcbs.jooq.db.tables.pojos.CbsInfo fetchOneByPartnerId(String value) {
        return fetchOne(CbsInfo.CBS_INFO.PARTNER_ID, value);
    }

    /**
     * Fetch records that have <code>VERSION IN (values)</code>
     */
    public List<tjcbs.jooq.db.tables.pojos.CbsInfo> fetchByVersion(Integer... values) {
        return fetch(CbsInfo.CBS_INFO.VERSION, values);
    }
}
