/*
 * This file is generated by jOOQ.
 */
package tjcbs.jooq.db.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;

import tjcbs.jooq.db.tables.CbsSavingsAccountLimit;
import tjcbs.jooq.db.tables.records.CbsSavingsAccountLimitRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CbsSavingsAccountLimitDao extends DAOImpl<CbsSavingsAccountLimitRecord, tjcbs.jooq.db.tables.pojos.CbsSavingsAccountLimit, Record2<String, String>> {

    /**
     * Create a new CbsSavingsAccountLimitDao without any configuration
     */
    public CbsSavingsAccountLimitDao() {
        super(CbsSavingsAccountLimit.CBS_SAVINGS_ACCOUNT_LIMIT, tjcbs.jooq.db.tables.pojos.CbsSavingsAccountLimit.class);
    }

    /**
     * Create a new CbsSavingsAccountLimitDao with an attached configuration
     */
    public CbsSavingsAccountLimitDao(Configuration configuration) {
        super(CbsSavingsAccountLimit.CBS_SAVINGS_ACCOUNT_LIMIT, tjcbs.jooq.db.tables.pojos.CbsSavingsAccountLimit.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<String, String> getId(tjcbs.jooq.db.tables.pojos.CbsSavingsAccountLimit object) {
        return compositeKeyRecord(object.getId(), object.getNino());
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<tjcbs.jooq.db.tables.pojos.CbsSavingsAccountLimit> fetchById(String... values) {
        return fetch(CbsSavingsAccountLimit.CBS_SAVINGS_ACCOUNT_LIMIT.ID, values);
    }

    /**
     * Fetch records that have <code>NINO IN (values)</code>
     */
    public List<tjcbs.jooq.db.tables.pojos.CbsSavingsAccountLimit> fetchByNino(String... values) {
        return fetch(CbsSavingsAccountLimit.CBS_SAVINGS_ACCOUNT_LIMIT.NINO, values);
    }

    /**
     * Fetch records that have <code>MAXIMUM_OVERDRAFT IN (values)</code>
     */
    public List<tjcbs.jooq.db.tables.pojos.CbsSavingsAccountLimit> fetchByMaximumOverdraft(Integer... values) {
        return fetch(CbsSavingsAccountLimit.CBS_SAVINGS_ACCOUNT_LIMIT.MAXIMUM_OVERDRAFT, values);
    }
}
