/*
 * This file is generated by jOOQ.
 */
package tjcbs.jooq.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import tjcbs.jooq.db.tables.CbsAccount;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CbsAccountRecord extends UpdatableRecordImpl<CbsAccountRecord> implements Record3<String, Double, Double> {

    private static final long serialVersionUID = 1723595179;

    /**
     * Setter for <code>APP.CBS_ACCOUNT.ID</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>APP.CBS_ACCOUNT.ID</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>APP.CBS_ACCOUNT.ALLOCATED_AMOUNT</code>.
     */
    public void setAllocatedAmount(Double value) {
        set(1, value);
    }

    /**
     * Getter for <code>APP.CBS_ACCOUNT.ALLOCATED_AMOUNT</code>.
     */
    public Double getAllocatedAmount() {
        return (Double) get(1);
    }

    /**
     * Setter for <code>APP.CBS_ACCOUNT.CURRENT_AMOUNT</code>.
     */
    public void setCurrentAmount(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>APP.CBS_ACCOUNT.CURRENT_AMOUNT</code>.
     */
    public Double getCurrentAmount() {
        return (Double) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Double, Double> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Double, Double> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return CbsAccount.CBS_ACCOUNT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field2() {
        return CbsAccount.CBS_ACCOUNT.ALLOCATED_AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return CbsAccount.CBS_ACCOUNT.CURRENT_AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component2() {
        return getAllocatedAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component3() {
        return getCurrentAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value2() {
        return getAllocatedAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getCurrentAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsAccountRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsAccountRecord value2(Double value) {
        setAllocatedAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsAccountRecord value3(Double value) {
        setCurrentAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsAccountRecord values(String value1, Double value2, Double value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CbsAccountRecord
     */
    public CbsAccountRecord() {
        super(CbsAccount.CBS_ACCOUNT);
    }

    /**
     * Create a detached, initialised CbsAccountRecord
     */
    public CbsAccountRecord(String id, Double allocatedAmount, Double currentAmount) {
        super(CbsAccount.CBS_ACCOUNT);

        set(0, id);
        set(1, allocatedAmount);
        set(2, currentAmount);
    }
}
