/*
 * This file is generated by jOOQ.
 */
package tjcbs.jooq.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import tjcbs.jooq.db.tables.CbsCustomer;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CbsCustomerRecord extends UpdatableRecordImpl<CbsCustomerRecord> implements Record5<String, String, String, Integer, String> {

    private static final long serialVersionUID = -984110675;

    /**
     * Setter for <code>APP.CBS_CUSTOMER.NINO</code>.
     */
    public void setNino(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>APP.CBS_CUSTOMER.NINO</code>.
     */
    public String getNino() {
        return (String) get(0);
    }

    /**
     * Setter for <code>APP.CBS_CUSTOMER.FIRST_NAME</code>.
     */
    public void setFirstName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>APP.CBS_CUSTOMER.FIRST_NAME</code>.
     */
    public String getFirstName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>APP.CBS_CUSTOMER.LAST_NAME</code>.
     */
    public void setLastName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>APP.CBS_CUSTOMER.LAST_NAME</code>.
     */
    public String getLastName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>APP.CBS_CUSTOMER.DOB</code>.
     */
    public void setDob(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>APP.CBS_CUSTOMER.DOB</code>.
     */
    public Integer getDob() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>APP.CBS_CUSTOMER.PRIMARY_EMAIL</code>.
     */
    public void setPrimaryEmail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>APP.CBS_CUSTOMER.PRIMARY_EMAIL</code>.
     */
    public String getPrimaryEmail() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, Integer, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, Integer, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return CbsCustomer.CBS_CUSTOMER.NINO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CbsCustomer.CBS_CUSTOMER.FIRST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CbsCustomer.CBS_CUSTOMER.LAST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return CbsCustomer.CBS_CUSTOMER.DOB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return CbsCustomer.CBS_CUSTOMER.PRIMARY_EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getNino();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getLastName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getDob();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getPrimaryEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getNino();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLastName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getDob();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getPrimaryEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsCustomerRecord value1(String value) {
        setNino(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsCustomerRecord value2(String value) {
        setFirstName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsCustomerRecord value3(String value) {
        setLastName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsCustomerRecord value4(Integer value) {
        setDob(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsCustomerRecord value5(String value) {
        setPrimaryEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsCustomerRecord values(String value1, String value2, String value3, Integer value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CbsCustomerRecord
     */
    public CbsCustomerRecord() {
        super(CbsCustomer.CBS_CUSTOMER);
    }

    /**
     * Create a detached, initialised CbsCustomerRecord
     */
    public CbsCustomerRecord(String nino, String firstName, String lastName, Integer dob, String primaryEmail) {
        super(CbsCustomer.CBS_CUSTOMER);

        set(0, nino);
        set(1, firstName);
        set(2, lastName);
        set(3, dob);
        set(4, primaryEmail);
    }
}
