/*
 * This file is generated by jOOQ.
 */
package tjcbs.jooq.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;

import tjcbs.jooq.db.tables.CbsCustomerEmails;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CbsCustomerEmailsRecord extends TableRecordImpl<CbsCustomerEmailsRecord> implements Record2<String, String> {

    private static final long serialVersionUID = -585992362;

    /**
     * Setter for <code>APP.CBS_CUSTOMER_EMAILS.NINO</code>.
     */
    public void setNino(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>APP.CBS_CUSTOMER_EMAILS.NINO</code>.
     */
    public String getNino() {
        return (String) get(0);
    }

    /**
     * Setter for <code>APP.CBS_CUSTOMER_EMAILS.EMAIL</code>.
     */
    public void setEmail(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>APP.CBS_CUSTOMER_EMAILS.EMAIL</code>.
     */
    public String getEmail() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return CbsCustomerEmails.CBS_CUSTOMER_EMAILS.NINO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CbsCustomerEmails.CBS_CUSTOMER_EMAILS.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getNino();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getNino();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsCustomerEmailsRecord value1(String value) {
        setNino(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsCustomerEmailsRecord value2(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsCustomerEmailsRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CbsCustomerEmailsRecord
     */
    public CbsCustomerEmailsRecord() {
        super(CbsCustomerEmails.CBS_CUSTOMER_EMAILS);
    }

    /**
     * Create a detached, initialised CbsCustomerEmailsRecord
     */
    public CbsCustomerEmailsRecord(String nino, String email) {
        super(CbsCustomerEmails.CBS_CUSTOMER_EMAILS);

        set(0, nino);
        set(1, email);
    }
}
