/*
 * This file is generated by jOOQ.
 */
package tjcbs.jooq.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import tjcbs.jooq.db.tables.CbsInfo;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CbsInfoRecord extends UpdatableRecordImpl<CbsInfoRecord> implements Record2<String, Integer> {

    private static final long serialVersionUID = -192094809;

    /**
     * Setter for <code>APP.CBS_INFO.PARTNER_ID</code>.
     */
    public void setPartnerId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>APP.CBS_INFO.PARTNER_ID</code>.
     */
    public String getPartnerId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>APP.CBS_INFO.VERSION</code>.
     */
    public void setVersion(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>APP.CBS_INFO.VERSION</code>.
     */
    public Integer getVersion() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return CbsInfo.CBS_INFO.PARTNER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return CbsInfo.CBS_INFO.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getPartnerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getPartnerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsInfoRecord value1(String value) {
        setPartnerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsInfoRecord value2(Integer value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsInfoRecord values(String value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CbsInfoRecord
     */
    public CbsInfoRecord() {
        super(CbsInfo.CBS_INFO);
    }

    /**
     * Create a detached, initialised CbsInfoRecord
     */
    public CbsInfoRecord(String partnerId, Integer version) {
        super(CbsInfo.CBS_INFO);

        set(0, partnerId);
        set(1, version);
    }
}
