/*
 * This file is generated by jOOQ.
 */
package tjcbs.jooq.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import tjcbs.jooq.db.tables.CbsProducts;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CbsProductsRecord extends UpdatableRecordImpl<CbsProductsRecord> implements Record2<String, String> {

    private static final long serialVersionUID = -1680301463;

    /**
     * Setter for <code>APP.CBS_PRODUCTS.PARTNER_ID</code>.
     */
    public void setPartnerId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>APP.CBS_PRODUCTS.PARTNER_ID</code>.
     */
    public String getPartnerId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>APP.CBS_PRODUCTS.PRODUCT</code>.
     */
    public void setProduct(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>APP.CBS_PRODUCTS.PRODUCT</code>.
     */
    public String getProduct() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return CbsProducts.CBS_PRODUCTS.PARTNER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CbsProducts.CBS_PRODUCTS.PRODUCT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getPartnerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getProduct();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getPartnerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getProduct();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsProductsRecord value1(String value) {
        setPartnerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsProductsRecord value2(String value) {
        setProduct(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsProductsRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CbsProductsRecord
     */
    public CbsProductsRecord() {
        super(CbsProducts.CBS_PRODUCTS);
    }

    /**
     * Create a detached, initialised CbsProductsRecord
     */
    public CbsProductsRecord(String partnerId, String product) {
        super(CbsProducts.CBS_PRODUCTS);

        set(0, partnerId);
        set(1, product);
    }
}
