/*
 * This file is generated by jOOQ.
 */
package tjcbs.jooq.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Record2;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import tjcbs.jooq.db.tables.CbsSimpleLoan;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CbsSimpleLoanRecord extends UpdatableRecordImpl<CbsSimpleLoanRecord> implements Record10<String, String, String, Integer, Integer, Double, Double, Integer, String, String> {

    private static final long serialVersionUID = 940593103;

    /**
     * Setter for <code>APP.CBS_SIMPLE_LOAN.ID</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>APP.CBS_SIMPLE_LOAN.ID</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>APP.CBS_SIMPLE_LOAN.NINO</code>.
     */
    public void setNino(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>APP.CBS_SIMPLE_LOAN.NINO</code>.
     */
    public String getNino() {
        return (String) get(1);
    }

    /**
     * Setter for <code>APP.CBS_SIMPLE_LOAN.CASA_ID</code>.
     */
    public void setCasaId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>APP.CBS_SIMPLE_LOAN.CASA_ID</code>.
     */
    public String getCasaId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>APP.CBS_SIMPLE_LOAN.FROM_DATE</code>.
     */
    public void setFromDate(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>APP.CBS_SIMPLE_LOAN.FROM_DATE</code>.
     */
    public Integer getFromDate() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>APP.CBS_SIMPLE_LOAN.TO_DATE</code>.
     */
    public void setToDate(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>APP.CBS_SIMPLE_LOAN.TO_DATE</code>.
     */
    public Integer getToDate() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>APP.CBS_SIMPLE_LOAN.PRINCIPAL</code>.
     */
    public void setPrincipal(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>APP.CBS_SIMPLE_LOAN.PRINCIPAL</code>.
     */
    public Double getPrincipal() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>APP.CBS_SIMPLE_LOAN.INTEREST</code>.
     */
    public void setInterest(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>APP.CBS_SIMPLE_LOAN.INTEREST</code>.
     */
    public Double getInterest() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>APP.CBS_SIMPLE_LOAN.INSTALLMENTS</code>.
     */
    public void setInstallments(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>APP.CBS_SIMPLE_LOAN.INSTALLMENTS</code>.
     */
    public Integer getInstallments() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>APP.CBS_SIMPLE_LOAN.PAYMENT_DUE</code>.
     */
    public void setPaymentDue(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>APP.CBS_SIMPLE_LOAN.PAYMENT_DUE</code>.
     */
    public String getPaymentDue() {
        return (String) get(8);
    }

    /**
     * Setter for <code>APP.CBS_SIMPLE_LOAN.STATUS</code>.
     */
    public void setStatus(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>APP.CBS_SIMPLE_LOAN.STATUS</code>.
     */
    public String getStatus() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, String, Integer, Integer, Double, Double, Integer, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, String, Integer, Integer, Double, Double, Integer, String, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return CbsSimpleLoan.CBS_SIMPLE_LOAN.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CbsSimpleLoan.CBS_SIMPLE_LOAN.NINO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CbsSimpleLoan.CBS_SIMPLE_LOAN.CASA_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return CbsSimpleLoan.CBS_SIMPLE_LOAN.FROM_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return CbsSimpleLoan.CBS_SIMPLE_LOAN.TO_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field6() {
        return CbsSimpleLoan.CBS_SIMPLE_LOAN.PRINCIPAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field7() {
        return CbsSimpleLoan.CBS_SIMPLE_LOAN.INTEREST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return CbsSimpleLoan.CBS_SIMPLE_LOAN.INSTALLMENTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return CbsSimpleLoan.CBS_SIMPLE_LOAN.PAYMENT_DUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return CbsSimpleLoan.CBS_SIMPLE_LOAN.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getNino();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCasaId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getFromDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getToDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component6() {
        return getPrincipal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component7() {
        return getInterest();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getInstallments();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getPaymentDue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNino();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCasaId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getFromDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getToDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value6() {
        return getPrincipal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value7() {
        return getInterest();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getInstallments();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getPaymentDue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSimpleLoanRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSimpleLoanRecord value2(String value) {
        setNino(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSimpleLoanRecord value3(String value) {
        setCasaId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSimpleLoanRecord value4(Integer value) {
        setFromDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSimpleLoanRecord value5(Integer value) {
        setToDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSimpleLoanRecord value6(Double value) {
        setPrincipal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSimpleLoanRecord value7(Double value) {
        setInterest(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSimpleLoanRecord value8(Integer value) {
        setInstallments(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSimpleLoanRecord value9(String value) {
        setPaymentDue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSimpleLoanRecord value10(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSimpleLoanRecord values(String value1, String value2, String value3, Integer value4, Integer value5, Double value6, Double value7, Integer value8, String value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CbsSimpleLoanRecord
     */
    public CbsSimpleLoanRecord() {
        super(CbsSimpleLoan.CBS_SIMPLE_LOAN);
    }

    /**
     * Create a detached, initialised CbsSimpleLoanRecord
     */
    public CbsSimpleLoanRecord(String id, String nino, String casaId, Integer fromDate, Integer toDate, Double principal, Double interest, Integer installments, String paymentDue, String status) {
        super(CbsSimpleLoan.CBS_SIMPLE_LOAN);

        set(0, id);
        set(1, nino);
        set(2, casaId);
        set(3, fromDate);
        set(4, toDate);
        set(5, principal);
        set(6, interest);
        set(7, installments);
        set(8, paymentDue);
        set(9, status);
    }
}
