/*
 * This file is generated by jOOQ.
 */
package tjcbs.jooq.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import tjcbs.jooq.db.tables.CbsSavingsTransactions;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CbsSavingsTransactionsRecord extends UpdatableRecordImpl<CbsSavingsTransactionsRecord> implements Record7<String, String, String, String, Integer, Integer, Double> {

    private static final long serialVersionUID = -300489983;

    /**
     * Setter for <code>APP.CBS_SAVINGS_TRANSACTIONS.ID</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>APP.CBS_SAVINGS_TRANSACTIONS.ID</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>APP.CBS_SAVINGS_TRANSACTIONS.NINO</code>.
     */
    public void setNino(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>APP.CBS_SAVINGS_TRANSACTIONS.NINO</code>.
     */
    public String getNino() {
        return (String) get(1);
    }

    /**
     * Setter for <code>APP.CBS_SAVINGS_TRANSACTIONS.TXID</code>.
     */
    public void setTxid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>APP.CBS_SAVINGS_TRANSACTIONS.TXID</code>.
     */
    public String getTxid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>APP.CBS_SAVINGS_TRANSACTIONS.LABEL</code>.
     */
    public void setLabel(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>APP.CBS_SAVINGS_TRANSACTIONS.LABEL</code>.
     */
    public String getLabel() {
        return (String) get(3);
    }

    /**
     * Setter for <code>APP.CBS_SAVINGS_TRANSACTIONS.TDATE</code>.
     */
    public void setTdate(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>APP.CBS_SAVINGS_TRANSACTIONS.TDATE</code>.
     */
    public Integer getTdate() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>APP.CBS_SAVINGS_TRANSACTIONS.TTIME</code>.
     */
    public void setTtime(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>APP.CBS_SAVINGS_TRANSACTIONS.TTIME</code>.
     */
    public Integer getTtime() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>APP.CBS_SAVINGS_TRANSACTIONS.AMOUNT</code>.
     */
    public void setAmount(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>APP.CBS_SAVINGS_TRANSACTIONS.AMOUNT</code>.
     */
    public Double getAmount() {
        return (Double) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<String, String, String> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, String, Integer, Integer, Double> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, String, Integer, Integer, Double> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return CbsSavingsTransactions.CBS_SAVINGS_TRANSACTIONS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CbsSavingsTransactions.CBS_SAVINGS_TRANSACTIONS.NINO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CbsSavingsTransactions.CBS_SAVINGS_TRANSACTIONS.TXID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return CbsSavingsTransactions.CBS_SAVINGS_TRANSACTIONS.LABEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return CbsSavingsTransactions.CBS_SAVINGS_TRANSACTIONS.TDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return CbsSavingsTransactions.CBS_SAVINGS_TRANSACTIONS.TTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field7() {
        return CbsSavingsTransactions.CBS_SAVINGS_TRANSACTIONS.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getNino();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getTxid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getLabel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getTdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getTtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component7() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNino();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTxid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getLabel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getTdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getTtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value7() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSavingsTransactionsRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSavingsTransactionsRecord value2(String value) {
        setNino(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSavingsTransactionsRecord value3(String value) {
        setTxid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSavingsTransactionsRecord value4(String value) {
        setLabel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSavingsTransactionsRecord value5(Integer value) {
        setTdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSavingsTransactionsRecord value6(Integer value) {
        setTtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSavingsTransactionsRecord value7(Double value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSavingsTransactionsRecord values(String value1, String value2, String value3, String value4, Integer value5, Integer value6, Double value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CbsSavingsTransactionsRecord
     */
    public CbsSavingsTransactionsRecord() {
        super(CbsSavingsTransactions.CBS_SAVINGS_TRANSACTIONS);
    }

    /**
     * Create a detached, initialised CbsSavingsTransactionsRecord
     */
    public CbsSavingsTransactionsRecord(String id, String nino, String txid, String label, Integer tdate, Integer ttime, Double amount) {
        super(CbsSavingsTransactions.CBS_SAVINGS_TRANSACTIONS);

        set(0, id);
        set(1, nino);
        set(2, txid);
        set(3, label);
        set(4, tdate);
        set(5, ttime);
        set(6, amount);
    }
}
