/*
 * This file is generated by jOOQ.
 */
package tjcbs.jooq.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import tjcbs.jooq.db.tables.CbsSimpleLoanPaymentSchedule;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CbsSimpleLoanPaymentScheduleRecord extends UpdatableRecordImpl<CbsSimpleLoanPaymentScheduleRecord> implements Record9<String, String, String, String, Double, Double, Double, Integer, String> {

    private static final long serialVersionUID = -736265804;

    /**
     * Setter for <code>APP.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.ID</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>APP.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.ID</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>APP.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.LOAN_ID</code>.
     */
    public void setLoanId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>APP.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.LOAN_ID</code>.
     */
    public String getLoanId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>APP.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.NINO</code>.
     */
    public void setNino(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>APP.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.NINO</code>.
     */
    public String getNino() {
        return (String) get(2);
    }

    /**
     * Setter for <code>APP.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.CASA_ID</code>.
     */
    public void setCasaId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>APP.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.CASA_ID</code>.
     */
    public String getCasaId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>APP.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.AMOUNT_DUE</code>.
     */
    public void setAmountDue(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>APP.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.AMOUNT_DUE</code>.
     */
    public Double getAmountDue() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>APP.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.PRINCIPAL_DUE</code>.
     */
    public void setPrincipalDue(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>APP.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.PRINCIPAL_DUE</code>.
     */
    public Double getPrincipalDue() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>APP.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.INTEREST_DUE</code>.
     */
    public void setInterestDue(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>APP.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.INTEREST_DUE</code>.
     */
    public Double getInterestDue() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>APP.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.AT_DATE</code>.
     */
    public void setAtDate(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>APP.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.AT_DATE</code>.
     */
    public Integer getAtDate() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>APP.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.STATUS</code>.
     */
    public void setStatus(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>APP.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.STATUS</code>.
     */
    public String getStatus() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, String, String, Double, Double, Double, Integer, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, String, String, Double, Double, Double, Integer, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return CbsSimpleLoanPaymentSchedule.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CbsSimpleLoanPaymentSchedule.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.LOAN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CbsSimpleLoanPaymentSchedule.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.NINO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return CbsSimpleLoanPaymentSchedule.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.CASA_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return CbsSimpleLoanPaymentSchedule.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.AMOUNT_DUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field6() {
        return CbsSimpleLoanPaymentSchedule.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.PRINCIPAL_DUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field7() {
        return CbsSimpleLoanPaymentSchedule.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.INTEREST_DUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return CbsSimpleLoanPaymentSchedule.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.AT_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return CbsSimpleLoanPaymentSchedule.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getLoanId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getNino();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCasaId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component5() {
        return getAmountDue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component6() {
        return getPrincipalDue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component7() {
        return getInterestDue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getAtDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLoanId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getNino();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCasaId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getAmountDue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value6() {
        return getPrincipalDue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value7() {
        return getInterestDue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getAtDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSimpleLoanPaymentScheduleRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSimpleLoanPaymentScheduleRecord value2(String value) {
        setLoanId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSimpleLoanPaymentScheduleRecord value3(String value) {
        setNino(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSimpleLoanPaymentScheduleRecord value4(String value) {
        setCasaId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSimpleLoanPaymentScheduleRecord value5(Double value) {
        setAmountDue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSimpleLoanPaymentScheduleRecord value6(Double value) {
        setPrincipalDue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSimpleLoanPaymentScheduleRecord value7(Double value) {
        setInterestDue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSimpleLoanPaymentScheduleRecord value8(Integer value) {
        setAtDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSimpleLoanPaymentScheduleRecord value9(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSimpleLoanPaymentScheduleRecord values(String value1, String value2, String value3, String value4, Double value5, Double value6, Double value7, Integer value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CbsSimpleLoanPaymentScheduleRecord
     */
    public CbsSimpleLoanPaymentScheduleRecord() {
        super(CbsSimpleLoanPaymentSchedule.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE);
    }

    /**
     * Create a detached, initialised CbsSimpleLoanPaymentScheduleRecord
     */
    public CbsSimpleLoanPaymentScheduleRecord(String id, String loanId, String nino, String casaId, Double amountDue, Double principalDue, Double interestDue, Integer atDate, String status) {
        super(CbsSimpleLoanPaymentSchedule.CBS_SIMPLE_LOAN_PAYMENT_SCHEDULE);

        set(0, id);
        set(1, loanId);
        set(2, nino);
        set(3, casaId);
        set(4, amountDue);
        set(5, principalDue);
        set(6, interestDue);
        set(7, atDate);
        set(8, status);
    }
}
