/*
 * This file is generated by jOOQ.
 */
package tjcbs.jooq.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import tjcbs.jooq.db.tables.CbsSavingsAccount;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CbsSavingsAccountRecord extends UpdatableRecordImpl<CbsSavingsAccountRecord> implements Record6<String, String, String, String, Double, Double> {

    private static final long serialVersionUID = -1067165756;

    /**
     * Setter for <code>APP.CBS_SAVINGS_ACCOUNT.ID</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>APP.CBS_SAVINGS_ACCOUNT.ID</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>APP.CBS_SAVINGS_ACCOUNT.NINO</code>.
     */
    public void setNino(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>APP.CBS_SAVINGS_ACCOUNT.NINO</code>.
     */
    public String getNino() {
        return (String) get(1);
    }

    /**
     * Setter for <code>APP.CBS_SAVINGS_ACCOUNT.NAME</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>APP.CBS_SAVINGS_ACCOUNT.NAME</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>APP.CBS_SAVINGS_ACCOUNT.CCY</code>.
     */
    public void setCcy(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>APP.CBS_SAVINGS_ACCOUNT.CCY</code>.
     */
    public String getCcy() {
        return (String) get(3);
    }

    /**
     * Setter for <code>APP.CBS_SAVINGS_ACCOUNT.BALANCE</code>.
     */
    public void setBalance(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>APP.CBS_SAVINGS_ACCOUNT.BALANCE</code>.
     */
    public Double getBalance() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>APP.CBS_SAVINGS_ACCOUNT.INTEREST</code>.
     */
    public void setInterest(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>APP.CBS_SAVINGS_ACCOUNT.INTEREST</code>.
     */
    public Double getInterest() {
        return (Double) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, String, Double, Double> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, String, Double, Double> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return CbsSavingsAccount.CBS_SAVINGS_ACCOUNT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CbsSavingsAccount.CBS_SAVINGS_ACCOUNT.NINO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CbsSavingsAccount.CBS_SAVINGS_ACCOUNT.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return CbsSavingsAccount.CBS_SAVINGS_ACCOUNT.CCY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return CbsSavingsAccount.CBS_SAVINGS_ACCOUNT.BALANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field6() {
        return CbsSavingsAccount.CBS_SAVINGS_ACCOUNT.INTEREST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getNino();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCcy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component5() {
        return getBalance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component6() {
        return getInterest();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNino();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCcy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getBalance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value6() {
        return getInterest();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSavingsAccountRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSavingsAccountRecord value2(String value) {
        setNino(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSavingsAccountRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSavingsAccountRecord value4(String value) {
        setCcy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSavingsAccountRecord value5(Double value) {
        setBalance(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSavingsAccountRecord value6(Double value) {
        setInterest(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CbsSavingsAccountRecord values(String value1, String value2, String value3, String value4, Double value5, Double value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CbsSavingsAccountRecord
     */
    public CbsSavingsAccountRecord() {
        super(CbsSavingsAccount.CBS_SAVINGS_ACCOUNT);
    }

    /**
     * Create a detached, initialised CbsSavingsAccountRecord
     */
    public CbsSavingsAccountRecord(String id, String nino, String name, String ccy, Double balance, Double interest) {
        super(CbsSavingsAccount.CBS_SAVINGS_ACCOUNT);

        set(0, id);
        set(1, nino);
        set(2, name);
        set(3, ccy);
        set(4, balance);
        set(5, interest);
    }
}
